### ISSUE TITLE
Issue related to 'Write MicroPython examples and tools for Portenta'  project

### ISSUE THREAD

**Issue by atharva-sundge** [arduino/summer-of-code#1]
In the project named 'Write MicroPython examples and tools for Portenta' ,dose Tensorflow library can be used or applied  for writing examples? 
And also in examples can we write Deep Learning example?

**Comment by Captain-Stack** [comment]
Hi I am an Undergraduate student and have some experience with micropython.Can you please tell me what kind of example code we can add in this issue?

**Comment by pra-dan** [comment]
The official docs/description says, it supports Jerryscript, micropython and Tensorflow Lite. So yes, I guess.

**Comment by thekunalsaini** [comment]
Hello all,
I am Kunal Saini from Kurukshetra, Haryana, India. I am a 3rd-year undergraduate student. I have worked on Arduino from very beginning i.e. from LED blinking to automation using IoT with IBM watson and building a mobile and robots using Arduino.
I have made lots of example .
Thank you,
Kunal Saini

Doubt:- Can we add an advance level example or basic one ?

Looking forward to becoming part of the Arduino Community and making contributions

**Comment by alranel** [comment]
Hello @a-v-s-coder, indeed you can use Tensorflow and work on Deep Learning.

@thekunalsaini Hello! You can make examples of any level. Advanced examples are very welcome.

**Comment by alranel** [comment]
Hello @a-v-s-coder, indeed you can use Tensorflow and work on Deep Learning.

@thekunalsaini Hello! You can make examples of any level. Advanced examples are very welcome. Please open a separate issue where we can communicate. We'd like to have one issue per student as a direct communication channel. :)

**Comment by atharva-sundge** [comment]
Ok sir, and thanks for replying @alranel 
I wanted to contribute  this project(Write MicroPython examples and tools for Portenta), please guide how to proceed further.

**Comment by alranel** [comment]
Hello @a-v-s-coder,

* make sure you read the [ideas list](https://github.com/arduino/summer-of-code/blob/master/ideas.md) (we recently added more ideas and more details)
* in order to write your proposal, follow the [guide](https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md)
* for any question, use this issue tracker and we will answer (but note: only one issue per student! write all your questions inside one issue)

**Comment by atharva-sundge** [comment]
Thanks, @alranel sir for replying.
 - I went through the updated ideas list.
 - Also, I get familiarised with Portenta specification available official site
 - Now, I am trying to implement MicroPython .

**Comment by atharva-sundge** [comment]
@alranel sir, I uploaded a draft proposal regarding the project 'Write MicroPython examples and tools for Portenta' on GSoC site.
Please take review and comment if possible.
Thank you!

Regard, 
Atharva Sundge
Email: avsundge@gmail.com

**Comment by atharva-sundge** [comment]
Update
1) Going through Micropython examples for Pyboard, as it may help in the project.
2)Working on AI and CV examples using TF Lite
3)Soon I will make one Hardware peripheral with Arduino Uno and will upload on ProjectHub, as it will give me some experience for the projection of work
@alranel sir looking forward to any suggestion before the result to be announced, as super excited to contribute to the project.
Thank you!

Regards,
Atharva Sundge
Email: avsundge@gmail.com
