### ISSUE TITLE
GSoC 2020|Portenta|Introducing myself

### ISSUE THREAD

**Issue by OmarAli3** [arduino/summer-of-code#100]
Hi all!
I’m Omar Ali, an Egyptian undergraduate computer engineering student, I am studying at faculty of engineering at Shoubra, Benha University, I am always enthusiastic for problem solving and learning new programming and scripting languages and skills, I love developing embedded systems and worked a lot with arduino different boards (uno, mega, mini , esp8266) and atmega32 from very basic projects to automation and advanced projects for nearly 3 years, also,I am familiar with Arm Cortex-M4 and currently working on TM4C123G LaunchPad.

I’m interested in the project of Writing MicroPython examples and tools for Portenta.

I made 2 pull requests in 2 different arduino libraries.
https://github.com/arduino-libraries/ArduinoSound/pull/24
https://github.com/arduino-libraries/ArduinoGraphics/pull/12

I have 1 question :
How many students will be selected for this project ?

**Comment by alranel** [comment]
Hello @OmarAli3, and thank you for your code contributions.
Regarding your question: we can't predict how many students will be selected. It will depend on the quality of the submissions, and also on the number of slots that Google will assign to Arduino.

**Comment by OmarAli3** [comment]
Hello @alranel, I have submitted my draft proposal nearly 10 days ago. Is there any hope to get a feedback before deadline ?

**Comment by OmarAli3** [comment]
New Pull Request in https://github.com/arduino-libraries/ArduinoGraphics/pull/16 .
