### ISSUE TITLE
Analyzer for Arduino libraries [or] Examples for official libraries

### ISSUE THREAD

**Issue by AnantaSrikar** [arduino/summer-of-code#101]
Hey there! I'm Ananta Srikar, a first year Computer Science student from Mahindra Ecole Centrale, Hyderabad, India. I have a 5 year expertise with C++, and also do a decent amount of Android App development, using Android Studio. I'm really interested in contributing to the Analyzer of the existing libraries. I'm also ok with working on the Examples for The official libraries. I suggest we make and Android app for the examples. Please let me know which one I can work on. My GitHub : [AnantaSrikar](github.com/AnantaSrikar)

**Comment by alranel** [comment]
Hello @AnantaSrikar. You are free to choose the project you prefer to work on. We listed both of them in the ideas page, so we support both. Developing an Android app however is not among the proposed ideas, so I'm afraid there would be no mentors available for it.

**Comment by AnantaSrikar** [comment]
Ok so how about I go ahead with the analyzer for the existing libraries? Please guide me as to what all I have to add to my draft to make it more acceptable.
