### ISSUE TITLE
GSoC'20 : Proposal FeedBack for "Write examples for the official libraries"

### ISSUE THREAD

**Issue by karanankit01** [arduino/summer-of-code#102]
Hi @alranel,
I have mailed you, my proposal for feedback. Kindly look into it and please give your comments on it.
My email I'd:- karanankit01@gmail.com
Thanks,
Ankit Karan

**Comment by alranel** [comment]
Hello @karanankit01, please use the GSoC web interface to submit your proposal. We are getting so many requests that we can't reply via e-mail individually.

**Comment by karanankit01** [comment]
Hi @alranel,
I have submitted the proposal draft via the GSoC website.

PS: I am working on the project "example for the libraries".
