### ISSUE TITLE
GsoC'20-Examples for official libraries(Arduino)|MicroPython Examples for portenta

### ISSUE THREAD

**Issue by Sapienscoding** [arduino/summer-of-code#103]
Hi,
I am Dhruv Sharma, an Electronics and Communication Engineering student. I am currently pursuing my bachelors in technology(ECE) in Maharaja Surajmal Institute of Technology, Guru Gobind Singh Indraprastha University. I always have zeal for the electronics and related stuff, like to build awesome things and programme them.
I have worked with different types of boards(UNO,Raspberry PI,) and used many sensors and peripherals. Therefore, i would like to enhance the examples for different libraries and provide the missing examples for different boards(Accelerometer and ESP8266), many faces problems when using these with arduino and they have to search and waste their time on web for useful content.
Secondly, I can write the Micro Python examples for your new board Portenta ; It will be a revolution for arduino to launch such board for the developing community. As i have a huge interest in assembling the hardware and finishing them into working products; i will provide you with the hardware implementation of those written examples of portenta.
I request you to kindly respond me as soon as possible, so that i can write the proposal to you. You can also contact me on this email:
dhruv337@gmail.com

**Comment by alranel** [comment]
Hello @sam337. Make sure you read the application guide in this repository as it contains instructions for writing a good project proposal.
