### ISSUE TITLE
[GSoC] Hi, I am Abhinav!

### ISSUE THREAD

**Issue by AbhinavMir** [arduino/summer-of-code#106]
I will be submitting a draft on JerryScript examples and libraries for Portenta. I am a junior at VIT, Vellore, majoring in CompSci. I have worked with Arduino since my Freshman year and worked on web development, blockchains and some core Computer Science. I use JavaScript as one of my core languages and supplement my projects with Arduino whenever needed (Like that one time I made a game controller in Uno). I used to be bad at documenting, but after a summer-long internship, I was forced to create a 150-page long documentations for my project. This helped me learn a lot of Markdown, Sphinx, Latex and the basics of creating interesting documentations. I am so excited to work with Portenta, with or without GSoC, I am a huge FOSS fanboy, and by extension, a (sometimes over-) enthusiastic fan of Arduino. I am excited to see what we can do for this cute, but powerful board, and I am so happy to see the community so enthusiastic about pushing forth the power of Open Source.

Maybe the fork be with you.
Abhinav.

**Comment by AbhinavMir** [comment]
Hi @alranel , I have submitted my first draft! Open to questioning and any changes, thank you for your time!

**Comment by alranel** [comment]
Hello @AbhinavMir, and thank you for submitting your proposal! We are overwhelmed with proposals so we are doing our best to review them. Make sure you keep improving it anyway without waiting for our feedback.

**Comment by AbhinavMir** [comment]
Sure!

**Comment by AbhinavMir** [comment]
Hi @alranel , just wanted to check in and know if there's any updates we could make to the draft!
