### ISSUE TITLE
[GSoC] write examples for official libraries (self introduction)

### ISSUE THREAD

**Issue by tkhabia** [arduino/summer-of-code#107]
hello,
My name is Tanmay khabia. I am in my 4th semester in IIIT Hyderabad. I have been using Arduino for my various home automation projects like visitor counters, smart street light & smart greenhouse farming.
In my beginner days, examples have been very helpful in understanding how to write code for new sensors like dht11. And I wish to contribute to this as my GSoC project. I have already made a pull request in one of the libraries for a requested example.
https://github.com/arduino-libraries/Arduino_LSM6DS3/pull/11/

1. As it is my first time writing an example can you tell me what is the correct way of writing an example in the library?
2. Also in many libraries, there is _no specific issue asking for more libraries_ but I wish to write some example which is practical in the field, so can I write an example in such a case? 
thank you

**Comment by tkhabia** [comment]
- Also, for the write MicroPython examples and tools for Portenta, what will be our interface with our board as our usual Arduino IDE will not work? 
- If we are not using Arduino IDE are we also unable to use the libraries also?
- the examples which we write should only contain the board only or we can add extra components also like external servo motor, LDR or some other sensor actuators.

**Comment by per1234** [comment]
>can you tell me what is the correct way of writing an example in the library?

Study the existing official examples for Arduino libraries. There are many of them. Use that as the reference.

The primary purpose of library examples is to provide a clear demonstration of the usage of the library to help people learn how to use it. There might be certain cases where an example showing a very common application for the library would be useful, but adding a lot of examples that are basically just sharing a project you did that happened to use the library is not very useful.

Keep in mind that people with very little knowledge of programming and electronics will be trying to use and understand the examples. It's essential to provide good documentation and make the code easy to understand and use. Things that seem obvious to you as someone with years of formal education in this field will not at all be obvious to the average Arduino user.

>Also in many libraries, there is no specific issue asking for more libraries but I wish to write some example which is practical in the field, so can I write an example in such a case?

Can you propose the addition of such examples as a volunteer contribution, unrelated to the GSoC program? Sure.

Can you propose the addition of such examples to fulfill the suggestion of fixing a bug as part of the [GSoC application phase](https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md#during-the-application-phase-february-20th---march-31st)? Perhaps this is useful as a demonstration of your work, but I don't think it counts toward our recommendation of submitting a fix for a bug. We are receiving a large number of example submissions, which are requiring a lot of time and effort to review. It's likely that very few of these examples will end up being accepted for addition to the official libraries. With your https://github.com/arduino-libraries/Arduino_LSM6DS3/pull/11, you did a good job of finding an issue report and submitting a fix for it, which is exactly what we recommended doing.

Can you propose the addition of such examples if you are accepted as one of the GSoC students working on the "adding examples for official libraries" project? Yes! We do need more examples for specific libraries that are currently lacking, and there are not necessarily existing issue reports for all of these.

**Comment by tkhabia** [comment]
I have submitted my draft proposal. Can you please give its review on it. It would be very helpful.
