### ISSUE TITLE
GSoC Introduction: Hi I am Dev

### ISSUE THREAD

**Issue by thesantatitan** [arduino/summer-of-code#108]
Hi, I am Dev. I am a first-year undergrad at [IIITD](iiitd.ac.in).
I have made several projects using microcontrollers in the past. The two most notable are:

- A snake game in processing which uses wireless Bluetooth control with gyro sensors

- This [project](https://siddharth19111.wixsite.com/magicl) which uses a nodeMCU and Arduino nano. The code for it is available on my Github account.

I have recently made a pull request fixing https://github.com/arduino/Arduino/issues/9801. The pull request is at https://github.com/arduino/ArduinoCore-avr/pull/322

I would like to apply for writing an analyzer for libraries or writing micropython examples for portenta and will soon upload my application

**Comment by alranel** [comment]
Hello @thesantatitan, welcome!
