### ISSUE TITLE
Self Introduction for -Write examples for official libraries

### ISSUE THREAD

**Issue by rez39** [arduino/summer-of-code#111]
This is Rajashekar Reddy , a junior in Electronics and Communication Engineering stream at International Institute of Information Technology,Hyderabad (IIITH), India. I am an Undergraduate Research student working in the field of Internet of Things mainly on Algorithms for Data reduction aiming for low power consumption, Air pollution monitoring, smart cities and Machine learning for constrained devices.

I am interested in contributing examples for the official libraries. One of the main reason I have decided to contribute is my experience working as a Teaching assistant for two courses (Embedded Systems Workshop and Introduction to IoT) which majorly deal and use Arduino IDE and Arduino based boards along with ESP based boards. My main responsibility was to guide the freshman who are completely new to the programming environment and Arduino and hence their understanding of the code and the examples provided were not enough. So I would like to contribute to example for the libraries which are interdependent on different libraries and I would like to mainly contribute to the Project hub with Hardware implementation of the Projects as I have comparatively more experience working with the implementation of the sensor nodes.

I would like to add examples to the libraries with sensors like DHT or actuators like Motors along with the existing examples for a complete project implementation.

**Comment by rez39** [comment]
@alranel I request you for feedback on the draft proposal I sent to the email summer-of-code@arduino.cc. and also through the GSOC Arduino page

**Comment by rez39** [comment]
I would like to ask if its possible to propose few projects (Intermediate and advanced level from end to end as a complete sensor and actuator node) for Projects hub under the examples for the official Libraries Idea, with no objective to add the examples to the official libraries.

**Comment by alranel** [comment]
@rez39 thank you for your submission! We are overwhelmed by project proposals so we are doing our best to review them. Please continue improving your proposal as much as you can without waiting for our feedback. Should you have any questions just write them here.
