### ISSUE TITLE
what about libraries not in github but are present on the official website

### ISSUE THREAD

**Issue by SadafShafi** [arduino/summer-of-code#112]
Hello, 
can someone tell me if we're are supposed to work only on the libraries mentioned here in github, or we can also contribute to that of other platforms, like` wire.h` happens to be for esp family and has a reference at Arduino.cc. what if I'd want to write examples for such libraries, is that allowed

**Comment by per1234** [comment]
>what about libraries not in github but are present on the official website

All of the official Arduino libraries are on GitHub.

>or we can also contribute to that of other platforms

The idea specifically says "write examples for official libraries", so I think you should stick to examples for Arduino's official platforms.

>wire.h happens to be for esp family and has a reference at Arduino.cc.

If you mean the Wire library, this library is available for all official Arduino platforms. It's also available for many 3rd party platforms, such as the Espressif platforms. Generally, although the implementation may be different, everyone follows the API of the official libraries. So if you write an example for Arduino's Wire library, it will likely also be useful to the users of 3rd party platforms as well.

The Wire library is architecture-specific, so a version of the library comes bundled with each platform. Here are the locations of the library for Arduino's official platforms:
- Arduino AVR Boards: https://github.com/arduino/ArduinoCore-avr/tree/master/libraries/Wire
- Arduino megaAVR Boards: https://github.com/arduino/ArduinoCore-megaavr/tree/master/libraries/Wire
- Arduino SAMD Boards: https://github.com/arduino/ArduinoCore-samd/tree/master
/libraries/Wire
- Arduino nRF528x Boards (Mbed OS): https://github.com/arduino/ArduinoCore-nRF528x-mbedos/tree/master/libraries/Wire
