### ISSUE TITLE
[GSOC] communication: Basanta Rijal

### ISSUE THREAD

**Issue by rijalbasanta** [arduino/summer-of-code#113]
Hello! This is Basanta Rijal, a Junior (3rd year) undergrad student in Electronics and Communication Engineering from Central Campus, Institute of Engineering, Tribhuvan University, Nepal.
I've had some knowledge and on field experience of the microcontrollers and microprocessors; as our course requirements as well as the projects in the Robotics Club in my college. This resulted in Arduino being my choice for the GSoC application.
I'd like to work on either 'Porting FreeRtos to Portenta' or 'Writing Examples for Official Library'

**Comment by alranel** [comment]
Hello @rijalbasanta, welcome. I recommend that you pick your project quickly and start writing your project proposal, following the application guide contained in this repository.

**Comment by rijalbasanta** [comment]
What will be the compiler used by IDE for portenta?

**Comment by rijalbasanta** [comment]
@alranel what compiler is going to be used in the IDE for Portenta?

**Comment by rijalbasanta** [comment]
@alranel Please provide feedback on my draft
