### ISSUE TITLE
GSoC @ Arduino, JerryScript for Portenta 🤩

### ISSUE THREAD

**Issue by noob-master147** [arduino/summer-of-code#114]
### Chears to GSOC and Arduino Community
Hey developers out there, my name is **Divyansh Khandelwal**. I'm 20 years and a sophomore at Vellore Institute of Technology. Getting to see Arduino as a GSOC organization was like a dream come true for me.

#### Something About Me
I got hands-on experience with Arduino about 20 months back and since then my thirst for learning and building projects has increased. I am an Electronics and IoT enthusiast and a backend developer in node.js. Till now I have built around 4 Industrial IoT projects and 2 backend projects. 
More about what I do is [**here**](https://drive.google.com/file/d/1Y8Ggp_UhPqsK5wdCHu2VQoqjj3VlHQF5/view?usp=sharing)
  
#### Project Proposal
I would wish to work on contributing JerryScript support to Portenta and building code support for the developers. I would also like to contribute towards the improvement of the documentation of Arduino and jerryscript. I also plan towards contributing to the **project hub** with a few of the hardware projects that I have built.

**Comment by therealbigzeez** [comment]
welcome @noob-master147

**Comment by alranel** [comment]
Hello @noob-master147, and welcome to the community! Thank you for introducing yourself and pointing to your past experience in IoT. I recommend that you pick a project quickly and start writing your project proposal, following the application guide that you find in this repository.

**Comment by noob-master147** [comment]
@alranel I hope you are best in health seeing the worsening situation in Italy due to COVID-19. 
@alranel since portenta isn't really available how can I contribute as of now to the community?
What I have in mind is adding a few Examples in the existing libraries and few in Arduino. What else can I do?

**Comment by noob-master147** [comment]
@alranel these are 3 of the Open PR I created yesterday, Do you have any suggestions or reviews about it?

**Comment by AbhinavMir** [comment]
Welcome @noob-master147 , good to see a fellow VITian here!
