### ISSUE TITLE
[GSOC'20] My wish is to work on idea: port FreeRTOS to Portenta

### ISSUE THREAD

**Issue by amritanshu-kk** [arduino/summer-of-code#115]
Hi There!
I'm Amritanshu Verma pursuing B.Tech degree with computer science engineering from Gurukula Kangri University, Haridwar, India.I'm a Developer Student Clubs Lead of my university at Google Developers.
My Projects:-
1.Chess game in C++
2.Multipurpose zero player game in C based on game of life algorithm.
( You can verify these projects in my github repository at @ amritanshu-kk )

I'm keen interested to work on one of your idea from the idealist: port FreeRTOS to Portenta.
Using the help of the community where i'm currently being connected and also with the help of this : https://www.freertos.org/FreeRTOS_Support_Forum_Archive/July_2006/freertos_Porting_guide_1537075.html.  I'll work on this project. 

I love to spend  my summer on the above idea.you can verify my experience through my projects in the github repository.I'm eagerly waiting for your positive response.
Contact Email:- amritanshu26dec@gmail.com

**Comment by alranel** [comment]
Hello @amritanshu-kk, and welcome!
Thank you for your introduction. I recommend you read the application guide contained in this repository and you start writing your detailed project proposal.

**Comment by amritanshu-kk** [comment]
Thank you @alranel for responding me!
