### ISSUE TITLE
Proporsal Feedback

### ISSUE THREAD

**Issue by salisbuk7897** [arduino/summer-of-code#116]
Hi everyone,
   @alranel I have sent my proposal to your email and will love to get your feedback on it. Thank you!

Regards,
Salisu Ali

**Comment by alranel** [comment]
Hello @salisbuk7897. Unfortunately we are receiving an overwhelming amount of requests, so e-mail is not the best channel. I recommend you use this GitHub issue or the official GSoC interface for submitting your proposal. If you have any questions, use this page for asking them. Thank you!

**Comment by salisbuk7897** [comment]
Hi @alranel, I have submitted a draft through the official GSoC website. Please I will like your feedback on it. Thank you!
