### ISSUE TITLE
Khushi Wadhwa - GSoC20 Applicant

### ISSUE THREAD

**Issue by khushi02** [arduino/summer-of-code#117]
Hey! My name is Khushi Wadhwa and I am a student at Carnegie Mellon University. I have a lot of experience working with Arduino for both personal and hackathon projects. I have around 5-6 years of programming experience, but I am new to the open source community. I hope to work with Arduino this summer on building new examples for existing libraries. 

Here is a link to my first example (submitted to the servo repository):
https://github.com/arduino-libraries/Servo/pull/46

**Comment by alranel** [comment]
Hello @khushi02.  Thank you for providing an example. Reminder: read the application guide carefully and start writing your project proposal.
