### ISSUE TITLE
Steven Silva - GSOC 2020 Applicant - write MicroPython examples and tools for Portenta

### ISSUE THREAD

**Issue by sasilva1998** [arduino/summer-of-code#119]
# Who am I?
I am a mechatronics engineering student, I will be coursing the seventh semester of ten by may. I am a open source and open hardware lover, like to contribute to these type of projects and have been doing that with github for about two year now. I am really interested and keen on every area involving robotics, ROS, microcontrollers, electronics, programming, AI and IoT, then I have been learning all about this topics in the last three years.

Additionally, I am cofounder of a community called FunPython here in Ecuador, which is commited to developing and sharing everything related to MicroPython, Python as well as other emerging technologies like AI and IoT. Since this community was founded about two years ago, I have been learning everything about MicroPython with Espressif microcontrollers and have even made PCBs with it. As you can see there are several projects I have contributed with in [FunPython's github account](https://github.com/FunPythonEC), some of them have been libraries, some examples, Jupyter Notebooks and projects.

Here is my CV just in case:
[Link to CV](https://espolec-my.sharepoint.com/:b:/g/personal/sasilva_espol_edu_ec/EVqYtQGQaKJHiZmDgwkhr_0BuYSXr6XDb3aflASSRBkZqA?e=6rwKbf)

# What is my goal?
I believe as well as FunPython community that MicroPython will be the next most used microcontroller languages and I want to support it as much as I can. We have even given around 20 talks about it here in Ecuador, including PyCon Colombia and FIT Guatemala. So our goal is promote MicroPython usage and develop solutions with it. 

# Why am I qualified to work on this idea
So far I have learned a lot about micropython, have made lots of examples about it, and so all this experience I have is enough to accomplish what is needed here, I have also ported some arduino libraries to micropython, created binaries and have been trying Maixpy software with Maixduino which is a little similar to Portenta.

Below some of these projects and examples are listed:
 * [Robot Soccer](https://github.com/FunPythonEC/Robot_soccer)
* [uPyArlo](https://github.com/sasilva1998/uPyArlo)
* [uPy Lewansoul LX-16](https://github.com/FunPythonEC/uPy_Lewansoul_LX-16)
* [AX12 uPy](https://github.com/FunPythonEC/AX12_uPy)
* [XL320 uPy](https://github.com/FunPythonEC/xl320_upy)
* [OV2640 uPy](https://github.com/FunPythonEC/OV2640_uPy)
There is also a project about a PLC which will be programmed with MicroPython:
* [PLC32](https://github.com/FunPythonEC/PLC32)

# What could I do?
Well for the project or idea, so far I don't know much about what Portenta can do or what are the built-in libraries, however, I could code example in Jupyter Notebooks as tutorials, could pass some CNN examples, in the way I would port any arduino needed library and if possible I would recreate my Robot Soccer project with Portenta adding a camera and image processing.

# What I would like to know?
I couldn't find much information about how Portenta is used, I have so far used only ESP8266 and ESP32 with MicroPython which can be programmed with several IDE (my favourite is just using rshell). So I would like to know how the workflow with Portenta is.

I will be attending any questions so feel comfortable to ask. Thanks in advance.

**Comment by alranel** [comment]
Hello @sasilva1998, and thank you for this introduction and the references to your past experience. Make sure you include that information in your project proposal (make sure you follow the application guide contained in this repository in order to write a good proposal).
Regarding your question, the workflow for using MicroPython on Portenta isn't much different from any other board supported by MicroPython. We are going to release the documentation and the code in the next few weeks (hard work is ongoing), but meanwhile you can take a look at the MicroPython documentation for other boards to get an idea.

**Comment by sasilva1998** [comment]
Hi @alranel, thank you for the info, yes I I have seen other boards like Pycon's, microbit, etc. And I am also now working on my proposal which will put as draft in the GSoC platform today.
