### ISSUE TITLE
Write examples and made tutorials for official libraries for efficient and effective use of library by developers

### ISSUE THREAD

**Issue by thekunalsaini** [arduino/summer-of-code#12]
I m Kunal Saini from Kurukshetra, Haryana, India.
I think this way of explaining is better because this have live demo with Example of library file usage.
Thank you,
Kunal

**Comment by thekunalsaini** [comment]
Hello all,
I am Kunal Saini from Kurukshetra, Haryana, India. I am a 3rd-year undergraduate student. I have worked on Arduino from very beginning i.e. from LED blinking to automation using IoT with IBM watson and building a mobile and robots using Arduino.
I have made lots of example .
Thank you,
Kunal Saini

Doubt:- Can we add an advance level example or basic one ?

Looking forward to becoming part of the Arduino Community and making contributions

**Comment by alranel** [comment]
@thekunalsaini advanced examples would be best. I'm closing this issue as it's a duplicate - let's keep just one issue per student.
