### ISSUE TITLE
where do we send our proposal for feed back

### ISSUE THREAD

**Issue by SadafShafi** [arduino/summer-of-code#120]
can someone please tell me where do I post/send my proposal to get feedback
Thank you for the help

**Comment by rez39** [comment]
> can someone please tell me where do I post/send my proposal to get feedback
> Thank you for the help
<br/>
You could do that from GSOC's Arduino page by clicking submit your proposal, then follow the steps given in the page. You would need to share the google docs link with "anyone with link can comment" access or link of any other preferred sharing platform
