### ISSUE TITLE
Add network discovery support to arduino-cli

### ISSUE THREAD

**Issue by JamolHojahon** [arduino/summer-of-code#121]
Hello, everybody!

I am Jamol, 1st year master of Russian-Tajik University, studying Computer Science in Dushanbe. I'm happy to find Arduino on the GSOC list.

I had some experience in web development with golang. Last year i learned and had experience in soft development and working with devices like cashcode, coinacceptor and printer custom VKP80II. 

For this summer of code, I'd like to work on a project **add network discovery support to arduino-cli**. I started to go deep into the details of the project. Can you point me towards an easy issue on start from?

**Comment by rsora** [comment]
Hi @JamolHojahon, I'm Roberto from the arduino-cli core developer team,
First of all thanks for your interest in contributing to the arduino-cli project, we are glad that you choose Arduino for your GSOC and personally, I'm glad that you choose the arduino-cli fo your contribution effort.

We had an internal discussion in the arduino-cli team and decided to propose a new activity on the CLI for the GSOC (see https://github.com/arduino/summer-of-code/pull/127) replacing the "network discovery" activity. 
We think that implementing the "external programmers" feature will provide great value to our community.

Feel free to check the relevant issue (https://github.com/arduino/arduino-cli/issues/27) and decide freely if you still want to contribute to the arduino-cli project. 
If you decide to go on in implementing the "external programmers" feature, please close this issue and open a new one, including  "_**arduino-cli external programmers feature**_" in the title, we will start to help you in your new issue.

Cheers from the arduino-cli team :+1:

**Comment by JamolHojahon** [comment]
Dear Mr @rsora,

Thank you sir. I'd be happy to work on the project **arduino-cli external programmers feature**.

I'm interested and can you tell me please where to start to get into it faster?

**Comment by rsora** [comment]
Very nice @JamolHojahon ! 
Please open a new issue with the project title (**arduino-cli external programmers feature**) and close this one, I'll give you some pointers to start!
