### ISSUE TITLE
Application for write MicroPython examples and tools for Portenta

### ISSUE THREAD

**Issue by shawayush** [arduino/summer-of-code#122]
Hi! I am a second-year CS under-grad. I have submitted a pull request that solves two of the bugs in Arduino Gui. The link is https://github.com/arduino/Arduino/pull/9908
I will be also working on two more issues that is #7658 and #6820 in the meantime. I request the mentors to guide me through the application writing process and I hope I can prove my worth in the meant time so that I can surely be selected.
I look forward to working with the arduino-group and learn some valuable skills, which I did while solving the bugs

**Comment by alranel** [comment]
Hello @shawayush, and thank you for the contributions. I suggest you read the application guide contained in this repository, that explains how to write a good project proposal. You will also need to pick a project among the ones listed in the ideas list.

**Comment by shawayush** [comment]
Hi @alranel Sir, I have gone through the applications guidelines, I look forward to working with MicroPython examples and tools for Portenta board!
Can I give a Draft application before I submit the final request? and what else, would you expect from in the Application Process.
And thank you much for seeing my PR and appreciating it, I hope I would prove you more valuable

**Comment by shawayush** [comment]
Hi @alranel, I have submitted a draft to Arduino, please give a feedback, so that I upgrade. That draft mostly covers the technical details and timelines. I hope the Proposal, is of your liking!

**Comment by shawayush** [comment]
hey @alranel, in the meantime I have attempted to solve two more issues.
https://github.com/arduino/ArduinoCore-samd/pull/511 and https://github.com/arduino/arduino-cli/issues/128 (almost there with the solution). I hope these contributions are enough to evaluate my application. 
Thank you
