### ISSUE TITLE
GSoC 20 :: Porting FreeRTOS to Portenta

### ISSUE THREAD

**Issue by UtkarshBhatthere** [arduino/summer-of-code#123]
Hey,
I am Utkarsh Bhatt, A senior year Electronics and Communications undergrad student at [National Institute of Technology Silchar](http://nits.ac.in/), India. I have been working on embedded systems for almost 3 years now. The list of micro-controllers i've worked on include {ATmega, STM8, STM32 (F0, F1, F4), ESP8266, and ESP32} for both custom firmware and Device Drivers Development. I've worked on FreeRTOS for ESP32 (using ESP-IDF, ADF) as well. Some of the my projects hosted on Github include the device drivers (SPI, USART, I2C) for STM32F4, FreeRTOS based applications for ESP32, and libraries  ported (lvgl) and written from scratch (libina). I am motivated for this project partly because of my respect towards Arduino being an opensource platform providing us with faster prototyping and development and partly because I've worked on Cortex M4 (STM32F429I) which is one of the core in Cortex H7 used in Portenta. I've never ported FreeRTOS to any hardware platform so this is a challenge for me as well. I am looking forward to have a discussion with the mentors on the project.

You can have a look at my [Repositories](https://github.com/UtkarshBhatthere) here.

Regards.

**Comment by alranel** [comment]
Hello @UtkarshBhatthere, and welcome. If you want to pick up the FreeRTOS porting project, you will find some guidance in the FreeRTOS documentation about porting. I recommend you read the application guide contained in this repository, in order to write a good project proposal.

**Comment by UtkarshBhatthere** [comment]
Thanks @alranel ,
I am going through the FreeRTOS porting documentation for now. Will finish writing the proposal soon. What about the coding proficiency test (Fixing issues on Arduino’s github repositories), Is there any specific issue you would like me to look into ?

**Comment by UtkarshBhatthere** [comment]
@alranel 
I’ve referenced some papers, tools and online documentations. I generated a shell project with FreeRTOS middleware on STMCube and found that FreeRTOS has been independently ported to CM4 and CM7 which means we can have a Asymmetric Multiprocessing model of FreeRTOS up and running. Hence I would like to know if the scope of project is inclined towards an SMP model or something completely different.
Regards.

**Comment by UtkarshBhatthere** [comment]
@alranel 
I have submitted the proposal kindly go through it and suggest any changes that you find required in the proposal. There are certain things that need to be discussed for the project I've mentioned them as a note in the proposal. I hope you find the proposal fitting.
Regards.
