### ISSUE TITLE
Make an official app for arduino to make Examples and tutorials available and lot more available to all(means handy to all)

### ISSUE THREAD

**Issue by thekunalsaini** [arduino/summer-of-code#13]
Its very helpful for many people.

**Comment by thekunalsaini** [comment]
Application of arduino for ios and andriod

**Comment by thekunalsaini** [comment]
These are instant preview of application.
 ##
(https://user-images.githubusercontent.com/43953836/75095529-9b3e0600-55bb-11ea-857a-b39f91b3cafa.jpg)

(https://user-images.githubusercontent.com/43953836/75095531-9d07c980-55bb-11ea-9dd4-231b49ae77fc.jpg)

(https://user-images.githubusercontent.com/43953836/75095533-9e38f680-55bb-11ea-9b0f-bfc65186faa8.jpg)

**Comment by thekunalsaini** [comment]
@masci @dcuartielles @tigoe @mbanzi

**Comment by derekdunes** [comment]
@shivang2k @Saurav80 ☝️

**Comment by thekunalsaini** [comment]
@derekdunes

**Comment by ayushontop** [comment]
Yeh

**Comment by thekunalsaini** [comment]
Thanks all to show interest

**Comment by alranel** [comment]
@thekunalsaini we currently have no mentors available for such project, because a native app is not in the roadmap. Examples should stay in the `examples/` directories of the libraries and be documented on the website at https://www.arduino.cc/en/reference/libraries

**Comment by thekunalsaini** [comment]
@alranel Can I mentor this project?

**Comment by alranel** [comment]
@thekunalsaini I guess you are applying as a student, not as a mentor.

I'm closing this one as you opened #47. Let's have only a single issue per student
