### ISSUE TITLE
GSoC 20 - Vinay Lanka - arduino-cli external programmers feature

### ISSUE THREAD

**Issue by vinay-lanka** [arduino/summer-of-code#130]
### Introduction

Hey!
I'm Vinay Lanka, a 20 year old ECE undergraduate at Vellore Institute of Technology. I am really excited to hear that Arduino is a mentoring organisation for GSoC 20. Arduino has been the first microcontroller that I'd ever come across during my school days. I still remember speding hours in trying to get various hardware components to work with the original Arduino UNO R1 board.

I am an electronics enthusiast and a fullstack web developer, with a proficiency in C,C++,Python and more recently Go. I've made and contributed to various projects that involve the use of the Arduino boards. You can checkout that and more in my website [here](vinay-lanka.github.io)

I have checked out the GitHub organisations and the repositories to get a sense of the task that lays ahead. I've participated in issues and made active pull-requests to the cli repository and I'm looking forward to fixing more issues.

#### Contributions 

- #595 - Improve output message with config file creation 
- #632 - update compile --build-path to support both relative and absolute flags 

### The project

I do understand the need for adding support for external programmers and see this as a welcome addition to the cli project.
Personally I have used various external programmers including the USBISP avr programmer, Parallel Port programmer and the AVR JTAG ICE programmer to program boards like the Arduino, 8051, etc.

I've checked out the upload function for the programmers in the java IDE and will work on formulating a proposal to implement support for the same.
I'll be glad if someone could link me to helpful resources for the same. 

Thank You,
Vinay Lanka

**Comment by rsora** [comment]
Hi @vinay-lanka,
Please have a look at our [CONTRIBUTING](https://arduino.github.io/arduino-cli/CONTRIBUTING/) section in our docs before start contributing.
[This section of our docs regarding the tooling](https://arduino.github.io/arduino-cli/platform-specification/#tools) is also a good place to start for getting the right context.
Happy coding!

**Comment by vinay-lanka** [comment]
@rsora, the docs are very helpful thanks!

**Comment by vinay-lanka** [comment]
Hey,
I've uploaded a draft of my proposal regarding this project on the GSoC dashboard. I would really appreciate if you guys could take a look and suggest changes and improvements.
Thank you!

**Comment by vinay-lanka** [comment]
Thank you so much for the opportunity!
It's a great experience contributing to open source and I am going to continue to try and contribute to the Arduino organisation.
