### ISSUE TITLE
Arduino-cli external programmers feature

### ISSUE THREAD

**Issue by JamolHojahon** [arduino/summer-of-code#134]
Hey!
I am Jamol, 1st year master of Russian-Tajik University, studying Computer Science in Dushanbe. I'm happy to find Arduino on the GSOC list.

I had some experience in web development with golang. Last year i learned and got experience in soft development and worked with devices like cashcode, coinacceptor and printer custom VKP80II.

P.S
Can you kindly recommend me an easy issue to start with?

**Comment by rsora** [comment]
Hi @JamolHojahon ,
Please give a look at [our issues here ](https://github.com/arduino/arduino-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)
And before start, read the [CONTRIBUTING](https://arduino.github.io/arduino-cli/CONTRIBUTING/) section of or documentation.
Happy Coding!
