### ISSUE TITLE
GSoC: Irum Ghafoor -- Seeking Guidance

### ISSUE THREAD

**Issue by IrumGhafoor** [arduino/summer-of-code#140]
Hello, My name is Irum Ghafoor and I am from Pakistan. I have worked with Raspberry Pi 4 using Python. 
I have experience in C++ as well. However, may I know that from where can I get started if I want to apply for Arduino's project(s)? Moreover,  I want to ask if having hardware is essential to work on any of the project(s) of the Arduino or are we good to go if we have Linux installed?

**Comment by panktishah62** [comment]
Hey @IrumGhafoor 
You can have a look at Arduino's ideas list and can choose one or more project that you would like to take up this summer. And then make a project proposal for the same.

Hardware would depend on what you want to implement.

Hope it helps!
