### ISSUE TITLE
How to know which library require examples or modification?

### ISSUE THREAD

**Issue by Engineer1999** [arduino/summer-of-code#15]
Hello all
I am trying to add or modify examples in the Arduino library but I don't know where to start. Can someone please help me in finding the issue or a library which need modification or need a new example.
Thank you.

**Comment by george-stam** [comment]
I would like to know too

**Comment by alranel** [comment]
You can go through the repositories in https://github.com/arduino-libraries (whose documentation is at https://www.arduino.cc/en/reference/libraries) and start from one that has no `examples/` directory.
