### ISSUE TITLE
GSoC idea @ making official Arduino android and ios testing mobile applications

### ISSUE THREAD

**Issue by annkkiit** [arduino/summer-of-code#155]

**Comment by ochui** [comment]
Hello @ankit2019j , please a look at @alranel  reply on issue #34

**Comment by annkkiit** [comment]
Can we build an iOS version of it?

**Comment by ashpande** [comment]
Please also see #13 and #17 , it appears that any kind of mobile application is not on their roadmap for this year. I know there is very little time remaining but it would be risky to go ahead with this.
