### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by hsntrq** [arduino/summer-of-code#164]
Hi, I am a Bachelors Of Science undergraduate at Habib University currently in my second semester pursuing a major in Computer Engineering. I wish to work on writing MicroPython examples for Portenta.

I wanted to know whether Portenta uses pyfirmata or some other library for MicroPython

**Comment by Ezraorich** [comment]
Hello, I am a last year Bachelor of Information Systems student at Eurasdian National University. Now I want to make some contribution.

**Comment by hsntrq** [comment]
Added MicroPython example for Portenta about sweeping a servo - https://github.com/arduino-libraries/Servo/pull/56
