### ISSUE TITLE
Write examples for official libraries

### ISSUE THREAD

**Issue by manoloramirez** [arduino/summer-of-code#169]
Hi! My name is Manolo Ramírez, I´m a Mechatronics Engineer from Guatemala and currently studying my Msc in Computer and Automation Engineering with specialization in Robotics & Automation in Italy. 
The first time I met the Arduino platform was in 2013. In March of that year I had to carry out my first project, modulating the voltage of an LED with a variable resistor. Since then I made diferrent proyects in my bachelor´s degree like:
- Controllers PID, discrete time controllers, magnetic levitators, 
- Industrial type aplications like sorters, controlling circuits for pneumatic actuators, different types of sensors 
- The classics like traffic lights, braitenberg vehicles and others. 
- Others.

I have plenty experience using different type of sensors, actuators and official/unofficial modules. Right now I have available the modules: HC-SR04, IR, Microphone, Barometric pressure, Photoresistor, Rotary Encoder, MQ-2 Gas, Humidity, Passive Buzzer, 5V, 12V and 24V relays, Power supply 3V - 5V, RF 433 MHz, WIFI and Ethernet, Heart Pulse; to be able to carry out tests and examples with different levels of complexity which will be useful for any student, curious person or Arduino enthusiast.

I´m specifically interested in doing examples for Engineering branch, in other words, making examples for the different electronic, control and even mechanical courses. When I was in my undergraduate degree, I realized that not everyone is able to make code from 0 when the basic theoretical concepts are not yet fully understood. However, I am also interested in other types of examples, if these are assigned to me.

I am grateful for the time it took to read my proposal and I would love to collaborate in the Open Source Comminity and Arduino.

**Comment by ashpande** [comment]
You have submitted a proposal on the Google site right?

**Comment by manoloramirez** [comment]
Yes, I submitted it yesterday.
