### ISSUE TITLE
NEW PROJECT: Flutter App for all the examples, tutorials and documentation 

### ISSUE THREAD

**Issue by shivang2k** [arduino/summer-of-code#17]
I would like to propose a new project for GSOC'20. The project will be focused on building a flutter app for Arduino, which shall contain all the tutorials regarding all the Arduino boards (New and Old), Examples for most of the libraries (As much as we can add) along with videos if available, and official documentation.

The reason why I am proposing to build a flutter app is that using the same code base we can develop apps for Android, IOS and Web. making this project highly scalable and of great advantage to the users.

I would like to add that with the skills I have, I can incorporate this project(Flutter App) with the proposed project "Write examples for official libraries". means along with writing the flutter app, I shall also develope examples for the Libraries and some How-to-Videos for the same.

Thank You

**Comment by SauravBaba** [comment]
@shivang2k  Sir I am very eager to work on this flutter app.Can I show some of user interface.

**Comment by derekdunes** [comment]
@shivang2k would definitely want to contribute too. Create a repo n a slack channel to start.

**Comment by alranel** [comment]
@shivang2k as of now, we don't have any mentors available for such project because a native app is not in the roadmap.
