### ISSUE TITLE
Question Regarding Gsoc 2021

### ISSUE THREAD

**Issue by Adhiraj10** [arduino/summer-of-code#170]
Will Arduino be a mentoring organization in the upcoming Gsoc 2021?
Thank you for taking your time out and answering the question :)

**Comment by Anky209e** [comment]
Yes,Of course it will be.

**Comment by D-Ajay-Kumar** [comment]
What projects will Arduino have this summer? And also can we have an IRC channel probably on Gitter for easy communication?

**Comment by alranel** [comment]
Hi @Tax3r @Anky209e @D-Ajay-Kumar, unfortunately Arduino is not applying for GSoC 2021.
However, any contribution to our open source projects is very welcome! Check out the various repositories and join the community :)
