### ISSUE TITLE
NEW PROJECT:  Developing Arduino 3D printer ,the libraries and their examples

### ISSUE THREAD

**Issue by mightycandle** [arduino/summer-of-code#18]
I'd like to propose a new project for the upcoming GSoC ,2020. This project will be focused on applications of arduino and  the libraries involved. This project takes up development of effiiceint codes for typical bot programs like _Micro-Mouse-Maze bot_, or be a _drone delivery_ and examples for all the libraries involved in it. 
    So rationally speaking, this would cover the examples for the libraries which we'll be using (like  `AFMotor` or `NewPing` ,etc.) and also to develop multi-functional bots. This would improve and refine Arduino on-field usage.
    You can find a Maze Solving bot's algorithm in my repository [https://github.com/mightycandle](url)
    I'm working on these libraries, analyzing them and developing examples. I'd like to refine and ensure that this would come out to a great prospect to the users.
    Another major contribution I'd like to put in is about _Morse Code_. Morse Code speeds up the communication. Morse Code is something which very important but rather has less development technologies.I'd like to efficiently make a library with functions referring to Morse Code language with led's put up on the board for digital output, and also, include proper examples from beginner level.
I'd kindly request the concerned people kindly review it and guide me through.

Thank you.

**Comment by pra-dan** [comment]
That sounds really promising! I would like to join this project in GSoC if possible.

**Comment by mightycandle** [comment]
Also, how should one contact the administrator?. I'm new to open source contribution and I have some queries about my projected project and about where to upload the examples .Could someone help me out in this?

**Comment by alranel** [comment]
Hello @mightycandle! Your idea sounds interesting and promising. You might want to start drafting a proposal using the template and the instructions included in this repository, and then just ask here any questions should you have. Let's use this issue as a direct communication channel between you and us.

**Comment by mightycandle** [comment]
Hey @alranel ,
Regarding the bots developement, I've come up with a few ideas, I wanna pursue all of them and I'd like to discuss with you its feasibility-
1. Blind drone RC: This is about making a drone-quadcopter with an arduino base, bluetooth connection to the Remote control and ultrasonic sensor for sensing, LEDs/ beep device( like an active buzzer). When the sensor senses an obstacle within a certain safe distance, the LED's or buzzer gives an output which will be seen/heard by the user controlling it, deending on the beep it gives , the user can turn let or right or up or down.
By using the buzzer system, even a blind man can control the drone with a remote control by listening to the signals. Also I'll be including library functions for the above
2. Line following bot : developing an efficient code and library functions  for a black tape line following bot using Infrared Sensor (IR)
3. Morse Code : Building library and inbuilt functions to develop communication tech.
Are these idea implementations fine? And if they're okay I'll work on milestones. Also nevertheless, I'll be focusing on more things like these if this is not feasible.
And I'm thinking about better models too. 
Can we be working on multiple bots and divisions like these during the Summer period? Since, Morse code is not directly related to the bots, I'm trying to develop a culmination.

P.S. : Yes I've seen the template and I'm working on it too :)

**Comment by alranel** [comment]
The things you describe already exist. You'll find such projects in [Project Hub](https://create.arduino.cc/projecthub), in the forum and around the web.  A GSoC project should be about _writing new software_ rather than creating bots with existing code. I suggest you have a new look at the [ideas list](https://github.com/arduino/summer-of-code/blob/master/ideas.md) (it was updated) to find inspiration. :)

**Comment by alranel** [comment]
But if you want to pursue the ideas you mentioned, you should explain how your project will be different from the existing ones and thus what _new_ code are you going to write.

**Comment by mightycandle** [comment]
Hello @alranel ,

I'd like to know, are there any mentors working in the field of Arduino for 3D Printing?
I'd like to introduce Home Automation for Arduino 3D Printers . (like for Arduino Materia 101)
(I have gone through the project forum and there was no project in this regard)

This project involves controlling the 3D Printer' attributes through arduino (Like motors for XYZ Movements , Stepper Motors, Thermistor, Two extruder ends, Data acquisition ) and its home automation. Precisely , I'd be using modules like ESP8266, SoftwareSerial,  HC05 Bluetooth, AFMotor, Stepper Motor, Servo, and some others too which are specified in the proposal I'm drafting.

Main division in this project is also dedicated to creating libraries with important automation functions of 3D Printing as in-built functions (class objects) in them.

I have very good exposure to 3D Printers (Club Head in my institute) ,its assembly and functioning and can even work on an actual model. Develop the actual product with this arduino project included.

Regards

**Comment by mightycandle** [comment]
Not just mentors directly into 3D Printing, mentor availability for any of the above modules is fine too.

**Comment by mightycandle** [comment]
@alranel 
Here is my project proposal. Please do check it out and inform me if any changes are required to it
Regards :)
https://drive.google.com/file/d/1i3BNogNVArIQuDc0L9z5H3RA9azREddK/view?usp=sharing

**Comment by mightycandle** [comment]
Hello @alranel 
I have submitted a draft proposal through GSoC portal and I request you to suggest if any changes are required to it so that I can finalize and send a pdf at the earliest.
Regards :)

**Comment by mightycandle** [comment]
Hello @alranel @rsora 
I have submitted a draft proposal through GSoC portal and I request you to suggest if any changes are required to it so that I can finalize and send a pdf at the earliest.
Or you can see it at:
https://drive.google.com/file/d/1i3BNogNVArIQuDc0L9z5H3RA9azREddK/view?usp=sharing
Regards :)
