### ISSUE TITLE
can former GSOC participants reapply?

### ISSUE THREAD

**Issue by dakhnod** [arduino/summer-of-code#23]
I was wondering if it would be possible for me and other former GSOC participants to apply for any of your projects when we have already completed GSOC once.

Are there any preconditions to be met in such a case?

**Comment by per1234** [comment]
Hi @dakhnod
From section 7.1b of https://summerofcode.withgoogle.com/rules/:
>A Student may not participate in the Program if:
...
>They have previously participated as a Student in Google Summer of Code two (2) or more times.

**Comment by dakhnod** [comment]
@per1234, thanks for the quick reply, I Just wanted to double check since some organizations decide to apply their own rules in some aspects...

**Comment by per1234** [comment]
I can't say whether Arduino is applying any additional restrictions on who can participate. Maybe one of the other administrators will comment here with that information.

**Comment by alranel** [comment]
@dakhnod We do not apply any additional restriction over the general GSoC rules. Feel free to propose your project :)
