### ISSUE TITLE
Can we apply for 2 projects/ideas ?

### ISSUE THREAD

**Issue by pra-dan** [arduino/summer-of-code#24]

**Comment by pra-dan** [comment]
I wish to apply for both:

1. Write examples for official libraries
2. Write MicroPython examples and tools for Portenta boards

Am I allowed to do so?

**Comment by alranel** [comment]
Yes, according to the GSoC FAQ: https://developers.google.com/open-source/gsoc/faq#can_i_submit_more_than_one_proposal
(Make sure you've read that guide)

**Comment by pra-dan** [comment]
Thank you.
