### ISSUE TITLE
GSoC '20: Deep learning imaging for Portenta

### ISSUE THREAD

**Issue by wizofe** [arduino/summer-of-code#29]
I am Ioannis and I am doing an MRes at King's College London in Medical Imaging and AI. Next year I will start a PhD and explore deep learning models in cardiac MRI reconstruction. Therefore I do have experience in imaging, some CUDA programming and 8 years of industry experience with hardware and software engineering.

In class, I have experience with PyTorch, MATLAB and Julia programming. I do know C++ and I am happy to use it as well. For this summer of code, I would like to propose a deep learning example tutorials, based on Portenta board.

I would like to discuss with you the best plan to go forward with my application from a mentor and of course what kind of contributions it makes sense to start with.

I appreciate your time.

Best wishes,

Ioannis

**Comment by alranel** [comment]
Wecome, Ioannis!

Your idea seems very interesting. Feel free to ask any questions should you have.

**Comment by wizofe** [comment]
Thank you @alranel!

I was thinking about creating similar tutorials, in the style of Tensorflow lite and Google Coral:
https://coral.ai/projects/minigo

or the Marshmallow sorter:
https://coral.ai/projects/teachable-sorter/

Is there anything you would like me to send for a PR, or should I write a proposal and send for feedback? :)
