### ISSUE TITLE
Write MicroPython examples and tools for Portenta

### ISSUE THREAD

**Issue by pkpale** [arduino/summer-of-code#3]
Hi, My name is Praveen Kumar. I'm an undergraduate student in the Electronics and Communication Department of NIT HAMIRPUR(H.P). I previously worked with the Arduino Uno board and STM32F746NG Board in my college curriculum project where I deployed Convolution Neural Network(CNN) on it using STM32CubeMx software. My programming languages are python, java, c++.
I don't have much exposure to open source but a few days back only I completed the udacity course on Git to get good insights on Git and Github which will be helpful in the project . I'm interested in the project  "Write MicroPython examples and tools for Portenta" .

**Comment by ANTRIKSH-GANJOO** [comment]
[Arduino.txt](https://github.com/arduino/summer-of-code/files/4239857/Arduino.txt)
[Arduino2.txt](https://github.com/arduino/summer-of-code/files/4239858/Arduino2.txt)
[Arduino3.txt](https://github.com/arduino/summer-of-code/files/4239859/Arduino3.txt)
#These are some of the examples in #5  for Portena Board

**Comment by tanmaythaakur** [comment]
Hello everyone. My name is Tanmay Thakur and I am a second year undergrad at Keshav Memorial institute of Technology, Hyderabad, majoring in ECE. I have prior experience of working with **Arduino UNO** and Wifi module **ESP8266**. I can work with programming languages like **Python, C, C++**. I would like to work on the project "**Write MicroPython examples and tools for Portenta**". Please provide a few pointers on how to get started. 
Awaiting your response.

**Comment by SahanWickramage** [comment]
Hello, I am Sahan who is an Integrated Computer Engineering final year undergraduate at the University of Moratuwa, Sri Lanka. I have done many Arduino projects. Some of them are the Arduino library for communication protocol and the Arduino quadcopter flight controller. I am interested in embedded systems and networking. I am familiar with Python and C++. I would like to contribute to "Write MicroPython examples and tools for Portenta". Could I get guidance to start contributing?

**Comment by alranel** [comment]
Hello everybody, some hints for you:

* make sure you read the [ideas list](https://github.com/arduino/summer-of-code/blob/master/ideas.md) (we recently added more ideas and more details)
* in order to write your proposal, follow the [guide](https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md)
* for any question, use this issue tracker and we will answer (but note: only one issue per student! write all your questions inside one issue)
