### ISSUE TITLE
Write examples for official libraries

### ISSUE THREAD

**Issue by KAbhijeet2105** [arduino/summer-of-code#30]
Hello Everyone,
I am Abhijeet Kadam from Kolhapur, Maharashtra, India. I have worked with Arduino Mega, Arduino UNO, Arduino Nano,esp8266 nodemcu. I developed many projects like a line-following robot, home automation, and other IoT projects by using Arduino boards. I have good knowledge of C, C++, Python and Java programming languages. I also have good experience in Android Development.
 I am interested in writing examples for the official library and in writing MicroPython examples and tools for Arduino Portenta. Looking forward to being part of the community. Thank you.

**Comment by alranel** [comment]
Welcome!

Some hints for you:
* make sure you read the [ideas list](https://github.com/arduino/summer-of-code/blob/master/ideas.md) (we recently added more ideas and more details)
* in order to write your proposal, follow the [guide](https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md)
* for any question, use this issue tracker and we will answer (but note: only one issue per student! write all your questions inside one issue)

**Comment by KAbhijeet2105** [comment]
Hello @alranel, Thank you so much for sharing this information and motivating me. I will list down my all PRs here.
https://github.com/arduino-libraries/Servo/pull/38
https://github.com/arduino-libraries/Arduino_HTS221/pull/3
https://github.com/arduino-libraries/Arduino_CRC32/pull/6
https://github.com/arduino-libraries/SD/pull/77
https://github.com/arduino-libraries/TFT/pull/17

**Comment by KAbhijeet2105** [comment]
@alranel  @per1234 I have submitted my Draft proposal on the official GSoC website. I would like to get your feedback on it. Thank you.

**Comment by KAbhijeet2105** [comment]
### Weekly report (1 April - 7 April 2020) 
**Work done :**

- Explored TFT Library

- [#18](https://github.com/arduino-libraries/TFT/issues/18): In the Arduino TFT library, there is a function to draw triangle but, the documentation and example are missing.

-  [#17](https://github.com/arduino-libraries/TFT/pull/17): Added new example Rainbow,added new example TFTTriangle.

**Comment by KAbhijeet2105** [comment]
### Weekly report (8 April - 14 April 2020)
**Work done:**

- Total 58 Libraries explored out of 90.

- [#17](https://github.com/arduino-libraries/TFT/pull/17): minor bugs and typo fix.

**Comment by KAbhijeet2105** [comment]
### Weekly report (15 April - 21 April 2020)

**Work done:**

- A total of 64 Libraries explored out of 90.

**Comment by KAbhijeet2105** [comment]
### Weekly report (22 April - 28 April 2020)

**Work done:**

- A total of 68 Libraries explored out of 90.

**Comment by AsherThomasBabu** [comment]
No offense, but the spelling should be **weekly** instead of **weakly**

**Comment by KAbhijeet2105** [comment]
> No offense, but the spelling should be **weekly** instead of **weakly**
Thanks for suggesting the correction.
