### ISSUE TITLE
New Project : creating library to connect Arduino IDE and Python Script on local machine in real time

### ISSUE THREAD

**Issue by pinaki-sen** [arduino/summer-of-code#31]
Hello Everyone, 
I am **PINAKI SEN**, a second year student, pursuing B.Tech in Electrical Engineering from National Institute of Technology, Agartala.

As a part of **GSoC'2020**, I would like to work on a new Library for Arduino for creating a real time connection between the Arduino IDE and another python script running on Local Machine. I have worked with Arduino Uno, Nano, Mega,  NODEMCU ESP82666 etc. While working I have faced a problem very often, that is using the data given by arduino board as a input for any other python script in real time, running on local machine. 

So a library can be created for Arduino IDE, that will be able to connect the arduino with the running python script. It will be a bidirectional process. Basically the sensor data that we visualize in the serial monitor of Arduino IDE will directly be fed as a input to a python script running in beckend and the output from that script will return to the IDE as input to the connected Arduino Board in real time.

Now a days Machine Learning is used almost everywhere due to its large number of available python libraries, which is not provided by any other languages by C++. But as we can't use the data output of Arduino board in real time, we can't train a ML model using that. It is quite hard to train a reinforcement learning based model using a bot made using Arduino. As a result virtual model based training is done in softwares like MATLAB.

But if we can create some library like this proposed one, it will make the connection between Arduino IDE and ML python script more easier and a bot can be trained in a real environment. 

Thanks & Regards.
Excited to join the Arduino Community.

**Comment by devvrat02** [comment]
Hello, 
My self Chetan Malviya ,I am achieving bachelors in Computer Science  at Shri Vaishnav Vidyapeeth Vishwavidyalaya. I work on various real time project by connecting the arduino to the cloud by using like azure Mysql and other cloud provider and i face various problems for connecting it therefore i like to work on that interfacing and i work on the arduino uno,nano,nodemcu esp8266
Thanks.

**Comment by alranel** [comment]
@senpinaki222 actually, there are many tutorials around the web that show how to communicate with an Arduino using the serial port. :) I suggest you look at the ideas list to get inspiration about something that is actually needed.
