### ISSUE TITLE
GSoC'20 : Some queries about JerryScript for Portenta

### ISSUE THREAD

**Issue by get-thepacket** [arduino/summer-of-code#32]
#### write JerryScript (JavaScript) examples and tools for Portenta

_This issue is totally GSoC related and the repository does not have significant information about any arduino project._

Some queries that I have are stated below -

* about Portenta Board
  * The board is available at this [link](https://www.thingbits.net/products/arduino-portenta-h7) but is quite expensive. But this isn't a problem as you're sending boards to the selected students (as specified in the Ideas list). The issue here is availability for working before drafting a proposal.
  * So, I looked online for some references about the board but couldn't find any. I only found pinouts of the board.
  * I need some references/documentation to read and make myself familiar with the board. It'll be a great help in writing a quality proposal.
* about JerryScript
  * I actually can't figure out how the board will execute JerryScript.
  * JerryScript requires many flags to be passed in the terminal and any failure to execute might be hard to debug.
  * So, if you provide information about API and libraries of the board, that would be a big plus in understanding the **how** part of implementing JerryScript.

As for myself, I have some experience in using Arduino and I am quite familiar with git and Github in the perspective of collaboration.
I eagerly look forward to add value to the organisation while improving myself, if luckily my proposal got accepted. 
Thanks!

**Comment by pra-dan** [comment]
#9

**Comment by therealbigzeez** [comment]
If you are unable to lay your hands on a board you can use [TinkerCad](https://www.tinkercad.com/), its free. It allows you to write code and simlate it.

**Comment by alranel** [comment]
JerryScript can run on Portenta on top of mbed. See [this documentation](https://os.mbed.com/javascript-on-mbed/) for reference.
