### ISSUE TITLE
Write MicroPython examples and tools for Portenta project 

### ISSUE THREAD

**Issue by thekunalsaini** [arduino/summer-of-code#33]
Libraries and tools

**Comment by thekunalsaini** [comment]
Hello, @alranel open direct communication channel as said by you :)

**Comment by thekunalsaini** [comment]
what type of tools you require for portenta and where we would test example code for portenta ?
Please tell @alranel

**Comment by thekunalsaini** [comment]
I have made it first other all will make an duplicate @alranel

**Comment by thekunalsaini** [comment]
I am Kunal Saini, 20 year old Computer Science student & this tracker provides a brief idea about my work with the Arduino platform.

I have proficiency in the following languages :

Python (Including MicroPython)
Embedded C
Java
C++
Since 2017 I have been working with Arduino boards. I have completed projects ranging from light blinking to making a flight controller on Arduino UNO board. I also have experience in using OpenCV for image processing tasks on resource constraint devices.
Also I am an active member of the Arduino Community by regularly posting on the Arduino HUB & Hackster.io. website.
Projects that I contributed shown in this website :

After working a lot with embedded electronics, I feel by coding this summer using micro python examples on the powerful Portenta H7 board, would give me a great learning opportunity to sharpen my skills in this new field of Tiny ML & hardware programming.

I have created a pull request Arduino-libraries which is an initial step in fixing the issue of incompatibility in error messages within different examples of the library. I have tried and tested the code on Arduino UNO before making this pull request and my pull request got merged.

Thank you,
Kunal Saini

**Comment by thekunalsaini** [comment]
These are some examples made by me in Micropython

[Arduino2.txt](https://github.com/arduino/summer-of-code/files/4282382/Arduino2.txt)
[Arduino.txt](https://github.com/arduino/summer-of-code/files/4282383/Arduino.txt)

**Comment by thekunalsaini** [comment]
@alranel Please see my initial effort.
Thank you,
your comments motivate us @alranel

**Comment by alranel** [comment]
I'm closing this one as you opened #47. Let's have only a single issue per student

**Comment by thekunalsaini** [comment]
-

**Comment by thekunalsaini** [comment]
okay
