### ISSUE TITLE
New Project: Android app with IDE and Examples for various libraries

### ISSUE THREAD

**Issue by NitishGadangi** [arduino/summer-of-code#34]
### Introduction
Hello, I am Nitish Gadangi. I'm an Electronics and Communication Engineering student, specializing in developing high-quality Android and Web Applications. Currently doing my B.Tech in JNTU Hyderabad.\
Have a look at my complete profile here https://nitishgadangi.github.io/
### Idea Proposal
I would like to post a new project idea for GSoC that can become a kind of host application for all the ideas mentioned for the GSoC2020.

As there is no official application from Arduino for Android and other mobile devices. It will be very helpful if we build an Android App which contains IDE and other tools, the same as that of the official IDE for Desktop devices. So that user can write compile and execute right from their Mobile Devices. Also, it will be more intuitive if we also include all the examples written for various open-source libraries and other required documentation right within the app.

I would prefer to go with the Native Android App as all the required libraries and support is readily available prominently for native android (JAVA/KOTLIN) and moreover, being an open-source project itself Android supports code dumping to external devices out of the box.

### Why this Idea?
I really think this project is very useful for many Arduino users as it opens doors to many who don't have access to Desktops and also make it easy to edit/write code at any instant more efficiently and easily as Mobile Devices are becoming more powerful and accessible to everyone, day by day.

Please let me know your views about my Idea.

Thank You,\
Looking forward to listening from you.

**Comment by NitishGadangi** [comment]
hey @alranel bro,\
It will be more intuitive to create a Gitter/Zulip/Slack channel for community discussions.
Please consider creating one, if not available now.

If there is one available already, please help me in finding it.

**Comment by NitishGadangi** [comment]
@alranel 
Bro, Could you please have a look into it and provide me feedback about the possibility of the project and availability of mentors for the same.

I think this project will help the Arduino community a lot.

**Comment by alranel** [comment]
@NitishGadangi I'm sorry, it seems there are no mentors available for that project.
Note that writing and compiling scripts from a mobile device is already possible thanks to [Arduino Create](https://create.arduino.cc).
