### ISSUE TITLE
Write MicroPython examples and tools for Portenta

### ISSUE THREAD

**Issue by alexandrefresnais** [arduino/summer-of-code#36]
My name is Alexandre Fresnais. I am French and I am studying at EPITA engineer graduate school.

## Abstract

My purpose is to write many examples and tutorials for Portenta board.
I want them to be clear as much as possible to be accessible for every beginners.
Of course, I would like to gradually make them more difficult and more technical.

Then, when I will have familiarize myself with the team and the Portenta board, I would like to give my help by writing tools.

## Technical Details

If possible, I would like to redact webpages to make it easy for everyone to access information.

#### Community Bonding Period

Integrate myself into the community.
Learning how to properly code and redact as you are waiting for.
Receiving and playing along with the Portenta board to familiarize myself with it.
Begin to test scripts.

#### Phase 1

Write a beginners guide and basic examples in MicroPython.
I do not know if you will have suggestions but I guess it will be using LEDs and basic electronics.

#### Phase 2

Advanced examples and how to properly use Portenta like a boss.
At that time, I will be more inclined to write tools for Portenta boards as I will be familiarized with the team and the board.

#### Final Week

Submitting what is not submitted, adding some corrections, and give my best to produce the nicest result.

## Development Experience

As you can see in my GitHub portfolio there are few projects.
You will find an Optical Character Recognition Software written in C and you will find a python reinforcement learning AI.

I have been working with python for more than 2 years now at school so I have a pretty good level on it and overall I can adapt and learn by myself if necessary.

But what is more important is my Arduino experience.
I have been playing for years with Arduino (Nano, Uno, and Mega) with my schoolmate. (The last birthday present I offered to him was an UNO).
We have been playing with a lot of electronics, and we have made an universal 433Mhz controller.

In High School, I have been the team leader for an electronic project for the French baccalaureate.
We have made a robotic arm controlled by an Arduino using motors and relays.

## Why this project?

This project would remind me the good old time when I was playing with Arduino in my friend's basement with nearly no lights. 

I may be a little bit busy for the first two weeks of May for my finals, but I will manage to keep being involved in the project.

Thanks for reading my submission !

**Comment by alranel** [comment]
Hello @alexandrefresnais, make sure you have read the application guide in this repository and post your proposal through the GSoC procedure. Thank you!
