### ISSUE TITLE
GSoC 2020 - deepaklorkhatri007

### ISSUE THREAD

**Issue by lorforlinux** [arduino/summer-of-code#37]
Hi,
My name is Deepak Khatri and I am pursuing B.E. from Netaji Subhas Institute of Technology, New Delhi, India. I want to work on this project this summer.

I have created a pull request arduino-libraries/SD#73 which is an initial step in fixing the issue of incompatibility in error messages within different examples of SD library. I have tried and tested the code on Arduino UNO before making this pull request.

**Comment by lorforlinux** [comment]
I am interested in the following project,
> Idea: write examples for official libraries
>Many of the official libraries need more examples in order to help users understand how they can > be used. Examples are located in the same repository as the library itself.
>    Languages: C++
>   Difficulty: Easy/Medium (according to the libraries complexity)
>   Note: your application should contain a list of libraries that need examples and which you would like to work on.

I will work on solving another issue now and let you know here only :)

**Comment by lorforlinux** [comment]
Fixed the link for editor provided in the CustomCharacter example which was broken and replaced with a working editor link. 
pull request: https://github.com/arduino-libraries/LiquidCrystal/pull/31

**Comment by alranel** [comment]
Thank you for your contributions @deepaklorkhatri007 :-)

**Comment by lorforlinux** [comment]
My pleaseure @alranel, I am working on the proposal and will add some more examples soon :)
