### ISSUE TITLE
Project : Writing MicroPython , JerryScript (JavaScript) and examples and tools for Portenta

### ISSUE THREAD

**Issue by yvkrishna** [arduino/summer-of-code#38]
Hey Guys,
I am Vedha Krishna from Amrita Viswa Vidyapeetham ,
This year i want to participate in gsoc 2020 and being a ECE Student i am much more connected to this project. I have done quiet a few projects using Uno and Nano.I have recently worked on a project integrating arduino with bolt IoT and wrote a conference paper. I believe that this board would definitely help many researchers in robotics. Being a Full stack Web developer I do know Javascript and python so I believe that i can work for this project in both languages.

**Comment by yvkrishna** [comment]
Hello 
How to contact the mentor for protenta. I have few doubts

**Comment by alranel** [comment]
@yvkrishna, as explained in the README you can ask all your questions here. :-)
