### ISSUE TITLE
Write examples for official libraries

### ISSUE THREAD

**Issue by vaibhavjain30699** [arduino/summer-of-code#39]
Hey, My name is Vaibhav Jain, a 3rd-year student at the Indian Institute of  Information Technology and Management, Gwalior. I have worked with Arduino Uno in many of my projects including an "Intelligent Queue Management System using RFID". I started working with Arduino in class 12th and since then I have been working with it to create many projects.

I would like to work on the project "Write examples for official libraries" in GSoC'20. 

Also, I have a background as an Android Developer also, so definitely I can contribute to App Development as others were proposing ideas for an app.

Thank you, everyone, and excited to join the Arduino Community.

**Comment by msarimhassan** [comment]
Hey, My name is Sarim Hassan,a 2nd year student of computer sciences at University of Lahore. I have worked on many university projects in c++. I want to work in an organization so that i can familiar with the market environment also i polish by skills .
I would like to work on the project "Write examples for official libraries"

**Comment by Shobhs13** [comment]
Hello! My name is Shobhit Sinha, a 2nd-year student at Thapar Insititute of Engineering & Technology, Patiala. Over the course of my stay, I've done projects on Arduino UNO for buggy and automated farm system.

I would like to work on the project "Write examples for official libraries". 

Looking forward to work with the community.

**Comment by sakshiseth** [comment]
Hey, I'm Sakshi Seth, final year student at Banasthali Vidyapith. Using Arduino UNO, I have built BMI calculator for a company named, "One Key Care" as a free lancing task. Currently I'm working on a project over GoLang for HackerRank, Bangalore, India.
I am interested to contribute to "Write examples for official libraries".

**Comment by alranel** [comment]
Welcome everybody! Please, stick to the guidelines: one issue per student. This one is @vaibhavjain30699's one. Thank you :)
