### ISSUE TITLE
Add network discovery support to arduino-cli

### ISSUE THREAD

**Issue by sciamp-dev** [arduino/summer-of-code#4]
Hello everyone!

My name's Dennis, I'm an Italian student enrolled in the bachelor in Engineering of Computing Systems at Politecnico di Milano. As of now, I'm ending my internship at Philips in The Netherlands as an Embedded Software Engineer. 

The project I'm interested in is the one to _add network discovery support to arduino-cli_.
I'm finishing my intership (still 3 weeks) so I don't have much spare time now, but I'd like to start working on an issue.
I checked out the [arduino-cli repo](https://github.com/arduino/arduino-cli/issues), and there are no issues marked as "first good issue", can you point me towards an "easy" one to start from? :)

Many thanks for the help!

**Comment by SahanWickramage** [comment]
Hello, I am Sahan who is an Integrated Computer Engineering final year undergraduate at the University of Moratuwa, Sri Lanka. I am familiar with Arduino but not much familiar with Arduino Command Line Interface. But I have started to being familiarized with Arduino Command Line Interface. Recently I did the Arduino library for communication protocol and software using NPCAP. I am interested in embedded systems and networking. I have a good knowledge of networking fundamentals. I am familiar with Python, C, and C++ and started learning golang. I would like to contribute to "Add network discovery support to arduino-cli". Could I get guidance to start contributing?

**Comment by alranel** [comment]
(@SahanWickramage, let's keep one issue per student as an individual communication channel - feel free to open your own issue!)

@sciamp-dev, thank you for your message. We added the "good first issue" to a few issues there. Let me know if you have any more questions :)

**Comment by rsora** [comment]
Hi @sciamp-dev , I'm Roberto from the arduino-cli core developer team,
First of all thanks for your interest in contributing to the arduino-cli project, as @alranel mentioned, you can find [good first issues here](https://github.com/arduino/arduino-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22), feel free to pick one of them and start contributing!

We had an internal discussion in the arduino-cli team and decided to propose a new activity on the CLI for the GSOC (see https://github.com/arduino/summer-of-code/pull/127) replacing the "network discovery" activity. 
We think that implementing the "external programmers" feature will provide great value to our community.

Feel free to check the relevant issue (https://github.com/arduino/arduino-cli/issues/27) and decide freely if you still want to contribute to the arduino-cli project. 
If you decide to go on in implementing the "external programmers" feature, please close this issue and open a new one, including  "_**arduino-cli external programmers feature**_" in the title, we will start to help you in your new issue.

Cheers from the arduino-cli team :+1:

**Comment by sciamp-dev** [comment]
Thank you for the update @rsora! I checked it out and I'll switch to that.

I started writing a project proposal and I'll work on a first issue in the weekend. As soon as I have a draft, I'll open a new issue.

Sorry for the delay, I just ended my internship in the Netherlands and I'm quite busy finding a way to go back to Italy :weary:

**Comment by sciamp-dev** [comment]
Hello, sorry for the late update.
Since I was hired for an intership this summer, I no longer submitted a proposal.

Thanks anyway for the help! I'll try to stay involved with the community :)
