### ISSUE TITLE
GSOC'20 - Contributing to Arduino!

### ISSUE THREAD

**Issue by gokulp01** [arduino/summer-of-code#40]
Hello Arduino community!

I am Gokul, a 2nd-year undergrad from India. I would like to use this issue tracker to introduce myself and list the projects I want to contribute to. 

Having had my hands dirty on various MicroPython projects on various boards like the ESP8266, the Sparkfun Pyboard, I have come to a realization that there barely any official examples for a beginner to begin with. But, the same is not the case with Arduino, there are enough examples to begin off with, but with increasing complexity of the project, the number of examples also keep reducing. That being said, Arduino's projects " **write MicroPython examples and tools for Portenta** " and " **write examples for official libraries** " at the GSOC 2020 is a great initiative and has caught my interest and I'd love to contribute to such amazing projects. 

I have been a part of many projects in the field of embedded systems, the most noticeable contributions being in the field of embedded systems to make India's first fully autonomous car from scratch. Other than that, I have had a lot of experience working on the Arduino, the Raspberry Pi, STM32, ESP8266, Pyboard, TIVA, TI Hercules and a lot more. With this being said, I'd be delighted to start contributing to Arduino on a long term basis and augment a great value to the team and also learn a lot in the process. 

Eagerly waiting for someone to guide me further on the projects!
 
Have a great day!

**Comment by gokulp01** [comment]
I am also attaching to this issue tracker, a pull request (which solves a very persistent issue), which is generally the first step to contributing :)

https://github.com/arduino-libraries/Audio/pull/2#issue-382007475

**Comment by alranel** [comment]
@thelowercaseguy welcome and thank you for the code contribution. Make sure you follow the application guidelines contained in this repository and feel free to ask any question.
