### ISSUE TITLE
Contributing to Arduino

### ISSUE THREAD

**Issue by ghost** [arduino/summer-of-code#41]
Hello everyone,
I am Debraj Maji a second year under-graduate from the department of Electrical Engineering Indian Institute of Technology Kharagpur. While I am new to open source I am fairly experienced about git and Arduino . Would like to contribute to the project ,discuss some new ideas and bring them into action.

**Comment by ghost** [comment]
I would like to port the algorithms standard template library (only some specific ones) to the portenta board in micro python because I have read in some forums that the uno and the mega don't have support for it. I don't know how capable the hardware will be but at least it will be worth trying.

**Comment by alranel** [comment]
Hello @abhstract, can you provide more examples about your idea?

**Comment by ghost** [comment]
Sorry I think it won't be possible for me to contribute as I am locked down
in my home and have poor internet connectivity .
