### ISSUE TITLE
Introduction for GSoC 2020

### ISSUE THREAD

**Issue by pratikghule** [arduino/summer-of-code#42]
Hello everybody…Myself Pratik Ghule.
I am currently doing my Msc in computer science at Pune University in India.
I am topper of my class since my Bsc computer science.
I have scored a out off marks in maths. 
I am 22 years and begin active with gsoc since 3 years. 
My interested technologies are C,Cpp,Java,php,adv.java,adv.php,android,web development,game development,and many more. 
I have done two internships so far. 
My first internship was in web development building websites in html ,css , javascript and php. 
My second intership was in game development at kidaura pvt ltd, 
I used to develop my own solo games as well as maintain the existing games in 2d and 3d . 
I used Unity3d game engine and C# programming.

I am quick learner and would love to work in with the organization in gsoc’20. 
I am very good a documentation and find it really cool. 
I am responsible and punctual.

I have made a offline chat application in java in my graduation. 
And a Documenation on Beer shop management in second year.

This year I have made a android app for my college to carry out its daily operations as well as to for the teachers and students . 
The app lets the teachers notify students about daily notices and assignments and can even mark for every submitted or not submitted assignments. 
These apps have ease their work. 
I have been in this group from a quiet time. 
And have always thought of to be a gsoc student ever. 
Thank you!

**Comment by ToSeven** [comment]
Niu bi  🐂!!!!!!!!!!!!
you are so big!

**Comment by pratikghule** [comment]
Ya I am quite a good writer!

**Comment by pratikghule** [comment]
> Niu bi 🐂!!!!!!!!!!!!
> you are so big!

how should I begin for GSoC and contribution for org? can you guide?

**Comment by alranel** [comment]
@pratikghule please read the application guidelines contained in this repository and feel free to ask any question should something be not clear enough.
