### ISSUE TITLE
Write MicroPython examples and tools for Portenta

### ISSUE THREAD

**Issue by anaicagrouver** [arduino/summer-of-code#44]
I am Anaica Grouver, a sophomore Computer Science Engineering at PES University, India. I have come to know about the open source project to write MicroPython examples and tools for Portenta. This project immediately caught my attention as it is a brand new technology. I am extremely keen to take up this assignment as it will allow me to learn to use dual processor to deliver low latency operations on a customized hardware. Further, adding examples and tools for Portenta would help all the Arduino users.   

I am confident that I will be able to deliver as per the requirements as I have worked with Arduino Uno, LilyPad Arduino and NodeMcu along with intermediate to advanced level skills in C/C++ and Python. 

I am enclosing my resumé that describes my work done in the past. Kindly let me know how to take this forward and contribute to the project. 

TIA,
Anaica Grouver 

[Anaica.resume.pdf](https://github.com/arduino/summer-of-code/files/4278738/Anaica.resume.pdf)

**Comment by alranel** [comment]
Welcome @anaicagrouver, make sure you follow the application guide located in this repository that explains what to do.
