### ISSUE TITLE
Introduction for GSOC 2020 

### ISSUE THREAD

**Issue by vedrocks15** [arduino/summer-of-code#45]
I am Vedant Joshi, 20 year old Computer Science student from Indian Institute Of Information Technology Kottayam & this tracker provides a brief idea about my work with the Arduino platform.

I have proficiency in the following languages :
- Python (Including MicroPython)
- Embedded C 
- Java (Oracle Certified)

Since 2017 I have been working with Arduino boards. I have completed projects ranging from light blinking to making a flight controller on Arduino UNO board. I also have experience in using OpenCV for image processing tasks on resource constraint devices. 
Also I am an active member of the Arduino Community by regularly posting on the Arduino HUB & Hackster.io. website. 
Following are the projects that I have completed : 
- Basic Projects (https://create.arduino.cc/projecthub/vedrocks15) 
- Medium Level projects (https://www.hackster.io/vedrocks15)
- Using BlockChain to perform a secure M2M communication using MQTT protocol (https://drive.google.com/file/d/1fveob5iINRTrZVMgsVo2GZawICz8mpcz/view)
- Autonomous Drone to pick lemons (https://drive.google.com/file/d/1zUoipdWL84GqBzErEsgC3z5wCPCKwbgG/view)
- Running an encryption protocol on ESP32 using MicroPython (Ongoing)

I also own specialisation certifications in Deep Learning & TensorFlow.
After working a lot with embedded electronics, I feel by coding this summer using micro python examples on the powerful Portenta H7 board, would give me a great learning opportunity to sharpen my skills in this new field of Tiny ML & hardware programming.

**Comment by alranel** [comment]
Looking forward to see your proposal @vedrocks15! See the application guide in this repository.

**Comment by vedrocks15** [comment]
@alranel is it necessary for us to fix a bug & also is it necessary to write the pdf submission in markdown format ?
