### ISSUE TITLE
Writing Examples for Official Libraries

### ISSUE THREAD

**Issue by Rameshwar-dhakad** [arduino/summer-of-code#46]
Hello everyone
I am Rameshwar Dhakad 2nd year ECE undergraduate at National Institute of Technology Karnataka, Surathkal. I am new to GSoC. I am interested in" writing examples for Official libraries". I have used Arduino UNO, Atmega in some of my projects like Line and Light Follower Bot, automatic pill dispenser and many more. I am very much enthusiast to participate in this program.
I have one question-
what exactly we need to do in fixing a bug in given libraries?
I can find many repositories and many programs in that. Is there any error in those programs which we need to fix ?
there are many programs in those repositories how many we need to do?

**Comment by alranel** [comment]
@Rameshwar-dhakad the application guide contains some indications about that, with pointers to repositories of interest: https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md
