### ISSUE TITLE
GSoC 2020 - thekunalsaini

### ISSUE THREAD

**Issue by thekunalsaini** [arduino/summer-of-code#47]
I am Kunal Saini, 20 year old Computer Science student & this tracker provides a brief idea about my work with the Arduino platform.

I have proficiency in the following languages :

Python (Including MicroPython)
Embedded C
Java
C++
Since 2017 I have been working with Arduino boards. I have completed projects ranging from light blinking to making a flight controller on Arduino UNO board. I also have experience in using OpenCV for image processing tasks on resource constraint devices.
Also I am an active member of the Arduino Community by regularly posting on the Arduino HUB & Hackster.io. website.
Projects that I contributed shown in this website :
Website:- www.robozx.com

After working a lot with embedded electronics, I feel by coding this summer using micro python examples on the powerful Portenta H7 board, would give me a great learning opportunity to sharpen my skills in this new field of Tiny ML & hardware programming.

I have created a pull request Arduino-libraries which is an initial step in fixing the issue of incompatibility in error messages within different examples of the library. I have tried and tested the code on Arduino UNO before making this pull request and my pull request got merged.

Thank you,
Kunal Saini

**Comment by thekunalsaini** [comment]
Mentioned my project in this issue

**Comment by thekunalsaini** [comment]
https://github.com/arduino/summer-of-code/issues/33
https://github.com/arduino/summer-of-code/issues/13

**Comment by thekunalsaini** [comment]
@alranel I have written some basic example on micropython 
Please have a look
[Arduino.txt](https://github.com/arduino/summer-of-code/files/4322758/Arduino.txt)
[Arduino2.txt](https://github.com/arduino/summer-of-code/files/4322759/Arduino2.txt)

**Comment by thekunalsaini** [comment]
Currently working on jerryscript and micropython

**Comment by thekunalsaini** [comment]
Hello @alranel,
Please provide some suggestion and feedback, Happy to see.

**Comment by alranel** [comment]
Hello @thekunalsaini, your code looks promising! I suggest you start writing your proposal adding as many details as possible. This repository contains an application guide that you should follow.

**Comment by thekunalsaini** [comment]
Hi @alranel ,sure.
Thank you,
Kunal Saini

**Comment by thekunalsaini** [comment]
Hi @alranel,
Sir, I'm trying to submit proposal but website showing error at night.
Is there any other way to submit proposal.
I mailed to GSoC support for this issue.

**Comment by thekunalsaini** [comment]
@alranel urgent reply please

**Comment by luvneesh** [comment]
lol the time is up kid
