### ISSUE TITLE
Introducing Myself

### ISSUE THREAD

**Issue by santiagoCamp** [arduino/summer-of-code#49]
Hi! My name is Santiago Campos, i'm currently on my last year of university, i'm majoring in Mechatronics Engineering, i'm really interested in collaborating with you in GSoC, i'd like to coolaborate in the examples of libraries, i've worked for over 3+ years with Arduino and i'm quite familiar with the use of it and the development boards, i just have one question regarding the bug-fixing, what do we need to do? Do we need to send you the corrected version? Should we only tell you the problem or what? Please let me know.

**Comment by alranel** [comment]
@santiagoCamp the application guide in this repository contains some links to repositories where you can find open bugs. If you want to work on a bug, just use the normal GitHub workflow: comment in the issue and open a PR with your fix, referencing the original issue.
