### ISSUE TITLE
Introduction for GSoC 2020 : Write examples for official libraries

### ISSUE THREAD

**Issue by ken-suga** [arduino/summer-of-code#51]
Hello,
I am @ken-suga. I am an undergraduate student at a university in Japan. As I wrote on #7, I have some experience working with Arduino Uno and am a hobby user of AVR microcontrollers. I have C, C++, Python, Ruby and some assembly skills. I am highly interested in working on writing examples for official libraries, especially the mouse and keyboard libraries. Would you suggest me a bug that I should fix?
Thank you.

**Comment by alranel** [comment]
Hello @ken-suga, did you check the application guide? There are links to repositories and hints for finding open bugs. Let me know if you have any doubts.
