### ISSUE TITLE
Libraries analyzer

### ISSUE THREAD

**Issue by DmiitriyJarosh** [arduino/summer-of-code#52]
Welcome, my name is Dmitrii. I am 3d year student of Saint-Petersburg State University in Russia. My major is software engineering. I have some experience of working with Arduino boards and I am really excited with the idea of contributing to the software of Arduino. Personally, I want to work on the `idea of libraries analyzer`, as I am really interested in the topic of tools connected with static analysis.
Talking about my CV, you can find it [here](https://drive.google.com/open?id=1uwG8HUz91nw19keOEcWpoec2xI09gEIS).
I have some questions about analysis tool in development of which you are interested in:
* Do you have any prototype?
* Do you have any ideas of the model of the future analyzer or suggested prototype for it?

**Comment by alranel** [comment]
@DmiitriyJarosh we have no prototype. This task is about something that does not currently exist, so we are very open to discuss any good idea for it. Our language of choice for such backend tools is Go, so I'd expect that such project would combine Go for the crawling logic and C++ for the static analysis.

**Comment by DmiitriyJarosh** [comment]
@alranel Can you tell me about my next steps? Is it time to write proposal on the oficcial page of GSOC or I have to do something else before for successful application? If you want I can propose my own vision of future instrument in my prorposal and also provide a little plan of creating this instrument?
