### ISSUE TITLE
Introducing myself

### ISSUE THREAD

**Issue by Pratyush1606** [arduino/summer-of-code#53]
Hello! My name is Pratyush Jaiswal, I'm currently a 2nd-year student of Indian Institute of Technology Kharagpur majoring in Electrical Engineering. I'm really interested in collaborating with you in GSoC, I'd like to collaborate in writing MicroPython examples and tools for Portenta. I've worked for over 2+ years with Arduino and I'm quite familiar with the use of it and the development boards. Please let me know further procedures.
Thanks.

**Comment by alranel** [comment]
@Pratyush1606 see the application guide in this repository as it contains indications about what to do.
