### ISSUE TITLE
GSOC 2020 Introduction: MicroPython and JerryScript (JavaScript) examples and tools for Portenta 

### ISSUE THREAD

**Issue by aker99** [arduino/summer-of-code#54]
I am Himanshu Kotnala, 3rd year Computer Science undergrad student from DIT University Dehradun, India & this tracker provides a brief idea about my experience in developing IoT based projects.

I have proficiency in the following languages :
- Python (Including MicroPython)
- Embedded C
- JavaScript
- Java (Oracle Certified)

Since 2016 I have been working with Arduino boards and frameworks. I have completed projects ranging from the blinking of LED to a Home Automation system. I also have experience in web development and cloud deployment.

I have worked on live product of an end to end IoT based system Home Automation system during my internship. I feel by developing an example for the powerful Portenta H7 board using micro python and jerry script would give me a great learning opportunity to sharpen my skills.

**Comment by alranel** [comment]
Welcome to the community!
