### ISSUE TITLE
GSoC20: TensorFlow Lite for Portenta

### ISSUE THREAD

**Issue by laxsuryavanshi** [arduino/summer-of-code#55]
I am Laxmikant Suryavanshi, Third Year Student at SGGSIE&T. I have started exploring deep learning and used various models for image classification and object detection kind of projects. For GSoC20, I would like to create some deep learning projects that can be deployable on micro-controllers like Portenta development board and can be used for various purposes. I have experience in building and training deep learning models in PyTorch and TensorFlow.
I'd also like to work on creating new examples for Arduino's libraries. In fact, I've started working on it and also created my first pull request [https://github.com/arduino-libraries/Arduino_LSM6DS3/pull/10](url).
I would like to discuss with you further plans to go forward with my application from a mentor.
I appreciate your time.

**Comment by alranel** [comment]
@laxsuryavanshi feel free to ask any question by posting comments here, and also make sure you read the application guide contained in this repository.
