### ISSUE TITLE
[GSoC] Introduction and Idea

### ISSUE THREAD

**Issue by Abnaby** [arduino/summer-of-code#57]
Hello Everyone,
my name is Mohamed. I am a 2nd-year student at Ain Shams University in Egypt. My major is a mechatronics Engineer. I have some experience of working with Arduino boards  I've worked for over 3+ years with Arduino and I am really excited about the idea of contributing to the software of Arduino. Personally, I want to work on the idea of writing an analyzer for Arduino libraries, as I am really interested in the topic of tools connected with static analysis.
I have good knowledge of C, C++ and Java programming languages.
I need a hint to be qualified for this idea.

**Comment by alranel** [comment]
Hello @Abnaby, make sure you follow the application guide contained in this repository. Your proposal should be very detailed and describe well what you are going to do during the coding season.

**Comment by Abnaby** [comment]
Hello @alranel that's my proposal 
https://docs.google.com/document/d/1D8aHqvRvM71a215fuP10-FxWvlIIFijzf_WRb-NoGmU/edit?usp=sharing
Can you help me to improve my proposal?
