### ISSUE TITLE
 Analyzer for Arduino libraries

### ISSUE THREAD

**Issue by ochui** [arduino/summer-of-code#58]
Hello Everyone,
I am Ochui, Princewill from Nigeria. I have worked with a range of  Arduino boards including esp8266 
and nodemcu. I have good knowledge of C, C++, Python, and JavaScript. 

I am interested in the project which involves **writing an analyzer for Arduino libraries**. Looking forward to being part of the community. Thank you.

**Comment by ochui** [comment]
Hello @mbanzi , I have to questions I would like to ask.

**Comment by alranel** [comment]
Welcome @ochui! Make sure you follow the application guide contained in this repository, and feel free to use this page to ask any question.

**Comment by ochui** [comment]
Hello @alranel ! Thanks for the reply. I have submitted my proposal draft through the GSOC dashboard is it necessary for me the share it here?
