### ISSUE TITLE
Problem in finding libraries suitable for portenta board and portenta carrier. 

### ISSUE THREAD

**Issue by yshsaxena** [arduino/summer-of-code#59]
Dear Team Arduino,
Greetings,

I am Yash Saxena a second-year student pursuing a Bachelor of Computer Application, from Bhopal, Madhya Pradesh India.

I am a coding enthusiast, with over 5 years of hands-on learning in C, C++, and Python. With considerable knowledge of different operating systems includes Linux, macOS, and Windows. In a college project with knowledge of Arduino and its sketches, I had built a home automation system using Arduino, esp8266, and hc05.

For the proposed project, my primary submission is to port all possible examples of Arduino IDE into Micro-Python, to be used for Portanta.  For example, available sketches to support peripherals likes stepper motor, LCD, LED and more, with its basic working.

   
Also, In my primary glace on Portanta, it seems to be a futuristic device and to use it on its full potential

 with Portenta Carrier and other peripheral devices.

Q. Is there any already present library to support peripheral device like GSM, SD card, Camera and more?

Since in my research in Micropython.org I didn’t found any Library to support Portanta board.

 Q. Or is there is a possibility to write examples without a library? Yes/No, then please enlighten.

Hereby, I am posting some examples for your kind review. Looking forward for your precious comments.

For analogRead
```
# It reads the value from the analog device and print the value.
# Attach the center pin of a potentiometer to pin 1.


import machine                     # functions related to the hardware
import utime                       # time related functions

adc = machine.ADC(1)   # create an ADC object acting on a pin

utime.sleep(seconds)     # Sleep for the given number of seconds (NOT NEEDED).

val = adc.read_u16()     # read a raw analog value in the range 0-65535

print(val)               # print the value out

```
for LED_blink
```
#Blink

#Turns an LED on for one second, then off for one second, repeatedly.

from machine import Pin
import utime

p0 = Pin(0, Pin.OUT)

while 1:               #the while function runs over and over again forever.
	p0.value(1)        # turn the LED on.
	utime.sleep(1)     # Sleep for the given number of seconds.
	p0.value(0)        # turn the LED off.
	utime.sleep(1)     # Sleep for the given number of seconds

```
servo_sweep
```
# Sweep


import pyb             # Funtions related to the pyboard
import utime           # time related functions

myservo = pyb.Servo(1)   # create a servo object on position X1.
 
while 1:                       # the while function runs over and over again forever.
	for x in range(0,181):     
		myservo.angle(x, 1000)   # move servo to x degree and take 1000 milli second to get to the specified angle.
		utime.sleep(1)          # Sleep for the given number of seconds.


	for x in range(180,-1, -1):
		servo1.angle(x, 1000)
		utime.sleep(1)
```

**Comment by yshsaxena** [comment]
Is Portenta supports module like sim800l etc? or we have to use portenta carrier.

**Comment by pra-dan** [comment]
I may not be completely helpful here but I take the opportunity to mention some snippets that may help you...Regarding 
>Q. Is there any already present library to support peripheral device like GSM, SD card, Camera and more?

There is currently no support for the board, although it is almost time when we will have some of it. 

>For now, since we're finalizing the first code repositories, it's not possible to send early contributions. You can still send some contributions to another Arduino repo even if you plan to work on a Portenta.

and for
> Q. Or is there is a possibility to write examples without a library? Yes/No, then please enlighten.

The instructions say:

>MicroPython examples and **tools** for Portenta

So as far as I can infer, it means YES. Libraries should be considered as tools along with IDE add-ons applications ,etc.

**Comment by alranel** [comment]
Hello @yshsaxena. I'll try to answer your questions. The software stack for Portenta is under active development and will be released in the next few weeks. It will include the MicroPython stack (but with no libraries, so that's a good opportunity for your project proposal) and the core that allows running normal Arduino code, thus using the existing Arduino libraries.
Running MicroPython code on Portenta is not different than running it for any other board that supports MicroPython, so you can see the existing MicroPython documentation.
An idea could be to take examples from the embedded programming world (usually written in Arduino language, thus C) and turn them into MicroPython code.

> Q. Is there any already present library to support peripheral device like GSM, SD card, Camera and more?

Not yet, so you have plenty of room for proposing something.

> Q. Or is there is a possibility to write examples without a library? Yes/No, then please enlighten.

Good question there. It is possible, as long as you write the library as well along with the example.

**Comment by yshsaxena** [comment]
Dear @alranel 
Thank you for your really helpful response.  I will look forward to work with your suggestion.

Sincerely,

Yash
