### ISSUE TITLE
Introduction for project- "Writing examples for official libraries"

### ISSUE THREAD

**Issue by imraniac** [arduino/summer-of-code#60]
Hi, My name is Imran Alam, I m currently a Third Year Undergraduate Student from Jadavpur University studying Computer Science and Engineering, I m interested in working on the project titled "Writing examples for official libraries". I have beginner experience of working with Arduino and high proficiency in C++. In the past, I used to search how to use certain library functions (specific to my work) in StackOverflow and there are several others who do the same, thus I believe that the documentation/examples of some of the standard libraries lack a clear understanding of its functionality, which is my motivation for choosing this topic. I would like to know some libraries for which I should start working on.
Looking forward to your quick response, as the student application date is near.
Thank You

**Comment by alranel** [comment]
@imraniac you can find some useful guidance in the application guide contained in this repository as well as the ideas page. You should go through the existing libraries and choose the ones you think need more work in terms of examples, and you should list them in your project proposal along with some description of the work you're going to do on them.
