### ISSUE TITLE
write examples for official libraries and tutorials for official libraries and contributed libraries

### ISSUE THREAD

**Issue by ahmed-1997-hub** [arduino/summer-of-code#61]
Hi, I am Ahmed Khaled electrical and communication engineer senior student from Egypt.
I work in arduino projects around 5 years from a simple tasks to a complicated task manly arduino UNO. I know many programming languages and experience in C and C++ so the understanding of any library will not be an issue. I work on my collage as a part time TA so i can  explain examples and tutorials for any code or examples and I have made lots of example. and work with many libraries in arduino.

**Comment by alranel** [comment]
Welcome @ahmed-1997-hub. Just a reminder: follow the application guide contained in this repository in order to write a good project proposal.
