### ISSUE TITLE
Writing examples for library functions ...

### ISSUE THREAD

**Issue by sanjeev0008** [arduino/summer-of-code#62]
Hi this is Sanjeev kumaar an undergraduate student from India .....I have the skills on c c++ python ......and some assembly functions 
..I would like to contribute for this issue ......and very exciting to work on it .

**Comment by alranel** [comment]
Hello @sanjeev0008, welcome. Just a reminder: read carefully the application guide contained in this repository in order to understand how to write a good project proposal.
