### ISSUE TITLE
GSOC2020 - Jagmohan Singh

### ISSUE THREAD

**Issue by jmsingh6871** [arduino/summer-of-code#63]
I am Jagmohan Singh currently pursuing Btech(IT) from Guru Gobind Singh Indraprastha University and I  am working on Aurdinos Hardware and software for the last two years and now I want to contribute in Google Summer of Code to get some amazing experience while contributing in open-source. I want to work on these two ideas
Idea 1: write an analyzer for Arduino libraries
Idea 2: write examples for official libraries

**Comment by alranel** [comment]
Welcome @jmsingh6871. I suggest to pick one of those two ideas, as working on both would be too much. Also, remember to follow the application guide contained in this repository in order to understand how to write a good project proposal.
