### ISSUE TITLE
GSoc 2020 - asucada

### ISSUE THREAD

**Issue by asucada** [arduino/summer-of-code#64]
Hello everyone! My name is Anshul Chandra and, I'm a third year student at BITS Pilani pursuing B.E. Electronics and Instrumentation Engineering. I'm interested in the Idea: Port FreeRTOS to Portena.

My end goal is to port various API's like semaphores, event flags,fixed/variable length  memory pools, etc onto the Portena Board. This would help synchronize and communicate effectively between layers and devices on task systems.This has already been done for the LPC1718 using the LPC Expresso IDE and FreeRTOS. I will use this as a starting point  and implement the same on the Arduino IDE. 

I have experience in both high and low levels of programming languages and have worked with Arduino Uno/Mega, ATMEL/AVR microcontrollers, Proteus Design Suite. Look forward to contributing to Arduino!

**Comment by alranel** [comment]
Welcome @asucada! The RTOS task is an advanced one, so make sure you study the matter well and your proposal contains enough details and references. Feel free to use this page to ask any questions should you have.

**Comment by asucada** [comment]
Hello @alranel! I have spent this week writing the first draft for my proposal. Would appreciate it if you could give it a look and give me some advice. I am attaching the pdf version here. 
[arduinoproposal_asucada.pdf](https://github.com/arduino/summer-of-code/files/4370760/arduinoproposal_asucada.pdf)
