### ISSUE TITLE
GSOC 2020-pankti_shah

### ISSUE THREAD

**Issue by panktishah62** [arduino/summer-of-code#65]
Hello all !
My name is Pankti Shah, I am in my 2nd year at Pandit Deendayal Petroleum University, India studying Computer Science and Engineering.  I'm interested in working on the project titled "Writing examples for official libraries". I am proficient in C/C++ and I've built several projects using Aurduino UNO/Mega  boards which include intelligent cleaning robot, object detection and line following bots etc.

Also, I have a beginner experience in Machine Learning and Image processing.
I believe that proper examples and documentation of any library is necessary for anyone to understand its functionalities properly, which is the main reason I would love to work on this project.
Also, I would like to know from the mentors  which are the libraries I can start working on ?

Very excited to join Aurduino Community!!
Thankyou

**Comment by panktishah62** [comment]
@alranel @per1234 
How many examples do we have to write for one library ?
Like, I am interested in writing examples for 3 libraries :
1. Keyboard Library:
i) It does not have enough examples for modifier keywords, I would like to implement codes for using different functions.
ii) Also it does not have any examples for shortcuts that use 3 keys simultaneously (for ex: CTRL + ALT + "q")

2. Mouse Library:
i) It does not have examples for usage of its inbuilt functions together or combined with some other library.
ii)No proper indentation followed for existing examples.

3. Capacitive Sensing Library:
i) A project can be built by combining the use of keyboard( giving inputs from the board)
and the capacitive sensor.
ii)Also, the library does not have examples for usage of its inbuilt functions together.

Can you please guide me whether the examples I am planning to prepare are ample or I'll need to work on more libraries, if yes, what is the approximate number of examples I'll have to make ?

Waiting eagerly for your feedback as the application date is near.
Thank you for the long read !
Regards,
Pankti Shah

**Comment by alranel** [comment]
@panktishah62 the number of examples and libraries depends on the complexity of the examples. But considering the length of the coding season, you might want to work on approximately 5 examples, provided they are not too simple.
