### ISSUE TITLE
Write examples for official libraries

### ISSUE THREAD

**Issue by ash-xyz** [arduino/summer-of-code#66]
I think there's no better way to learn than to teach.

Hey there, I'm Ash.
I'm a Computer Science student in University College Dublin and I'm keen to learn anything and everything that I can!

**Comment by alranel** [comment]
Welcome @ash-xyz! You're right: there's no better way than to teach. That's why documenting your work is very important. Just a reminder for you: make sure you have read the application guide contained in this repository that explains how to write a good project proposal.

**Comment by ash-xyz** [comment]
> Welcome @ash-xyz! You're right: there's no better way than to teach. That's why documenting your work is very important. Just a reminder for you: make sure you have read the application guide contained in this repository that explains how to write a good project proposal.

If you don't mind, I have submitted a draft proposal and would love feedback!
Don't worry if you don't have the time, I understand that I'm a bit late to the party. 

Happy Hunting!
