### ISSUE TITLE
Cool & Clear Examples for Servo Library!

### ISSUE THREAD

**Issue by graydonhope** [arduino/summer-of-code#67]
Hey Arduino community!

I have been looking into the official Arduino libraries and see that one of the libraries doesn't have many examples. I believe we could improve the **Servo** library by writing some crystal clear code examples designated towards motor control. I want to focus on motor control since it is so prominent in the RC community (which in itself is very large). 

I already have the foundations of a hardware prototype which uses the Servo and SoftwareSerial libraries. This prototype has the potential to be developed into a detailed and engaging submission on ProjectHub. 

Improving on this library would highlight some of its potential and may engage more users into using it. 

I would love to discuss more technical details of the project and how I plan to incorporate multiple Arduino libraries in my technical documentation.

**Comment by graydonhope** [comment]
@alranel I am looking for some feedback on this idea and how I could make it more involved.

Thank you!

**Comment by graydonhope** [comment]
**Issues**
[Working with RS485 Shield Issue](https://github.com/arduino/Arduino/issues/9411)
[Working with Web Application Issue](https://github.com/arduino/Arduino/issues/9855)

**Comment by alranel** [comment]
@graydonhope that sounds promising. If you plan to work on a single library, your examples are going to be advanced ones. Make sure you describe them well in your project proposal. Are you planning to make hardware prototypes as well?

**Comment by graydonhope** [comment]
@alranel Thanks for the feedback. I will be focusing on two libraries and have described my plan in detail in my submitted proposal. Yes I am planning to make a hardware prototype. 
I suggested that I make advanced examples for the two libraries and then time-allowing I make additional examples for other libraries. These examples will be less involved without a hardware prototype. Does that seem like a good approach?
