### ISSUE TITLE
GSOC 2020 Introduction:Idea: write examples for official libraries or Idea: write MicroPython examples and tools for Portenta

### ISSUE THREAD

**Issue by ToSeven** [arduino/summer-of-code#68]
Hello everyone!
I am Jack, 21 years old, 3rd-year student majoring in computer science at Wuhan University. I have done some work on embedded development in my colleague, such as. the system design and implementation of  Quadrotor based on STM32 controller. So I have a rich experience for it. What is more, I have mastered the following languages and skills.
* C/C++ in Linux 
* Python 
* Makefile/Cmake/shell
* Operating system principle and Arm architecture 

Arduino is a wonderful project, I have ever used it to design automatic tracking robot. I think I have the ability to contribute to Arduino. Recently, I am planning to submit some code to the project.

very glad to join Arduino Community! Thanks all!

**Comment by Derekduke** [comment]
Hello Jack!
I appreciate your talent very much. It seems that we share similar interests and can communicate more in the future. Good luck.

**Comment by ToSeven** [comment]
哈哈哈哈 整中文吧😂

**Comment by ToSeven** [comment]
这个项目不好申啊 感觉好多人了。。。。。

**Comment by alranel** [comment]
Welcome @ToSeven! Make sure you read the application guide contained in this repository that explains how to write a good proposal, and feel free to use this page to ask any question.
