### ISSUE TITLE
Write examples for official libraries

### ISSUE THREAD

**Issue by Shobhs13** [arduino/summer-of-code#69]
Hello! My name is Shobhit Sinha, a 2nd-year student at Thapar Insititute of Engineering & Technology, Patiala. Over the course of my stay, I've done projects on Arduino UNO for buggy and automated farm system. 
I would like to work on the project "Write examples for official libraries".
Looking forward to work with the community.

**Comment by alranel** [comment]
Welcome @Shobhs13. Just a reminder: read the application guide contained in this repository that explains how to write a good project proposal.
