### ISSUE TITLE
Write examples for official libraries

### ISSUE THREAD

**Issue by ken-suga** [arduino/summer-of-code#7]
Hi,
I am @ken-suga . I am an undergraduate student at a university in Japan. I have some experience working with Arduino Uno and am a hobby user of AVR microcontrollers. I have C, C++, Python, Ruby and some assembly skills. I am highly interested in working on writing examples for official libraries, especially the mouse and keyboard libraries.
Is there a reason why no examples were created for these libraries?

**Comment by karanankit01** [comment]
Hii
I'm Ankit Karan currently a junior at Indian Institute of Technology, Mandi. I found the project for " Writing examples for official libraries " quite interesting. I have a good background in microcontroller basics and Robotics . I have working knowledge and good hand in C, C++ and Python .Also I am current coordinator of Robotics Club in IIT Mandi . Can you please suggest how to proceed further and contribute.
Thanks

**Comment by bhatakti-atama** [comment]
Hi, I would like to start working on this issue what would be a good place to start?

**Comment by sarthak-m-das** [comment]
Hi
I'm Sarthak M. Das. I am doing my undergraduates from BIT Mesra. I have an interest in Robotics and Embedded Systems. I have a working knowledge of C, C++, Python and JavaScript. I have some experience working with Arduino Uno. Also, I am contributing as the General Secretary of the Robotics Club of BIT Mesra. I am interested in working on the project "Write examples for official libraries". Can I get some suggestion about how to get started and contribute?
Thanks

**Comment by ken-suga** [comment]
Sorry, forgot to mention one thing. Could you suggest how I can get involved and contribute to this project?

**Comment by avinal** [comment]
Hello, 
I am Avinal. I am currently a junior at National Institute of Technology, Hamirpur, India. I find this project interesting. I have some experiences with Arduino Programming and I am very good at C++. Please suggest how to proceed further and contribute to this project. 
Thanks.

**Comment by PRITI24** [comment]
Hello,
I am Priti Jha.I am pursuing third year B.Tech Computer Engineering from Cummins College of engineering for Women in Pune.I also Contributed in Robocon 2019.I am interested in writing libraries.I am good at C,C++,Python,Java.I have worked with Arduino Mega,Arduino UNO,Arduino Nano.Can anyone help how to proceed further?

**Comment by derekdunes** [comment]
You guys should read the documentation again 👇https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md

**Comment by Engineer1999** [comment]
Hello all
I am Bhargav Patel from Ahmedabad, Gujarat, India. I am a 3rd-year undergraduate student. I have worked on Arduino extensively starting from LED blinking to automation using IoT and building a mobile robot capable of performing Simultaneous Localization and Mapping with Arduino and Java.

Doubt:- If already examples are available then can we make them more interpretable by adding comments? or Can we add a bit advance level example in library which already has an example?

Looking forward to becoming part of the Arduino Community and making contributions

**Comment by siddharth25pandey** [comment]
Hello, Myself Siddharth Pandey. I am doing my B-Tech in Computer Science Engineering from Indian Institute of Information Technology, Sri City. I have working knowledge in C,C++ and I also have experience in working with Arduino Uno. I am highly interested in working on writing examples for official libraries.
I have created a pull request https://github.com/arduino-libraries/ArduinoCloudThing/pull/54 which is an initial step in fixing the large value error messages in PUBLISH_INTERVAL_SEC in test folder within different examples of SD library. Can anyone help me what is the procedure and how to contribute for this project.

**Comment by thekunalsaini** [comment]
Hello all,
I am Kunal Saini from Kurukshetra, Haryana, India. I am a 3rd-year undergraduate student. I have worked on Arduino from very beginning i.e. from LED blinking to automation using IoT with IBM watson and building a mobile and robots using Arduino.
I have made lots of example .
Thank you,
Kunal Saini

Doubt:- Can we add an advance level example or basic one ?

Looking forward to becoming part of the Arduino Community and making contributions

**Comment by lorforlinux** [comment]
Hi, 
My name is [Deepak Khatri ](https://deepaklorkhatri007.github.io/)and I am pursuing B.E. from Netaji Subhas Institute of Technology, New Delhi, India. I want to work on this project this summer.

I have created a pull request https://github.com/arduino-libraries/SD/pull/73 which is an initial step in fixing the issue of incompatibility in error messages within different examples of SD library. I have tried and tested the code on Arduino UNO  before making this pull request.

**Comment by ANTRIKSH-GANJOO** [comment]
Hello,
I am Antriksh Ganjoo. I am pursuing  B.Tech Electronics Engineering from NIT Surat . I also Contributed in Robocon 2019. I am interested in writing libraries. I am good at C,C++,Python. I have worked with Arduino Mega,Arduino UNO,Arduino Nano.Can anyone help how to proceed further?

**Comment by alranel** [comment]
@ken-suga there's no reason why no examples were written for some libraries. That's why we need to write examples where needed :)

Hints for everybody:
* make sure you read the [ideas list](https://github.com/arduino/summer-of-code/blob/master/ideas.md) (we recently added more ideas and more details)
* in order to write your proposal, follow the [guide](https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md)
* for any question, use this issue tracker and we will answer (but note: only one issue per student! write all your questions inside one issue)

(I'm closing this issue because too many students wrote - let's have individual conversations)
