### ISSUE TITLE
GSoC 2020 - Vinay Lanka - Network discovery support to arduino-cli

### ISSUE THREAD

**Issue by vinay-lanka** [arduino/summer-of-code#70]
### Introduction
Hey!
I'm Vinay Lanka, a 20 year old ECE undergraduate at Vellore Institute of Technology. 
I am really excited to hear that Arduino is a mentoring organisation for GSoC 20. I've been using and tinkering with Arduinos since 6th grade. My earliest memory of the Arduino IDE is the splash screen that read, 
> An open project written, debugged and supported by @mbanzi , @dcuartielles , @tigoe ...,

and that quote had me wanting to contribute to the first platform that I have come across.

I am an electronics enthusiast and a fullstack web developer, with a proficiency in C,C++,Python and more recently Go. I've made and contributed to various projects that involve the use of the Arduino boards. You can checkout that and more in my website [here](https://vinay-lanka.github.io/)

I have checked out the GitHub organisations and the repositories to get a sense of the task that lays ahead. I have created an active pull request to add a small change to the arduino-cli repository and I'm working to fix more issues. 

#### The project

So after reading the project brief in the ideas file, adding network support would mean adding mDNS client support for service discovery right?
We could then make a seperate command for discovering these network boards.

I would also like to do some research for the same. If anyone can link me to the right resources, I'd be grateful. 

Thank You,
Vinay Lanka

**Comment by vinay-lanka** [comment]
#### Update
I would really like to contact someone to know more details about this project

**Comment by vinay-lanka** [comment]
Hey,

I drafted a proposal for review, any guidance on how to proceed?
Should I upload a pdf on the GSoC dashboard, or should I mail it to someone for a review?

Thank You,
Vinay Lanka

**Comment by alranel** [comment]
Hello @vinay-lanka, and welcome. Let's use this page for communication. You can link your proposal here and ask any questions should you have.

**Comment by vinay-lanka** [comment]
Hey @alranel , thanks for reaching out! 
I've uploaded the draft link on my GSoC dashboard. Should I link it here as well? Or only keep this thread for discussing doubts?
Thanks again! :)

**Comment by rsora** [comment]
Hi @vinay-lanka  , I'm Roberto from the arduino-cli core developer team,
First of all thanks for your interest in contributing to the arduino-cli project, as a proficient Golang contributor, you will provide to our community a great contribution for sure!

We had an internal discussion in the arduino-cli team and decided to propose a new activity on the CLI for the GSOC (see https://github.com/arduino/summer-of-code/pull/127) replacing the "network discovery" activity. 
We think that implementing the "external programmers" feature will provide great value to our community.

Feel free to check the relevant issue (https://github.com/arduino/arduino-cli/issues/27) and decide freely if you still want to contribute to the arduino-cli project. 
If you decide to go on in implementing the "external programmers" feature, please close this issue and open a new one, including  "_**arduino-cli external programmers feature**_" in the title, we will start to help you in your new issue.

Cheers from the arduino-cli team :+1:

**Comment by vinay-lanka** [comment]
Hey @rsora  ,

The new feature to add external programmer support does seem really promising and would be a welcome addition to the cli.

I am interested in contributing to this activity and would open a new issue for the same.
