### ISSUE TITLE
Gsoc 2020 Nedungadi Pranav V

### ISSUE THREAD

**Issue by npv12** [arduino/summer-of-code#71]
Hello all !
My name is Nedungadi Pranav V, I am in my 1st year at IIT Bhubaneswar, India studying Mechanical Engineering. I'm interested in working on the project titled "Writing examples for official libraries". I am proficient in C++ and Arduino, an intermediate in python and I've built some projects using Arduino UNO/nodeMCU which include, projects for fests like Techkriti, maze solving bots, RC vehicles , etc.

Also, I have a beginner experience image processing.
I believe that proper examples and documentation of any library is necessary for anyone to understand its functionalities properly and help them build their projects in a much better manner, which is the main reason I would like to work on this particular project.

Very excited to join Arduino Community!!
Thanking you

**Comment by alranel** [comment]
Welcome @npv12! Just a reminder: read the application guide contained in this repository that explains how to write a good project proposal.
