### ISSUE TITLE
GSoC 2020 - djdo

### ISSUE THREAD

**Issue by djdo** [arduino/summer-of-code#72]
Hello, my name is Diogo and I'm an Embedded Systems Master student from Portugal. 
Recently I've been dealing with real-time systems and multitasking, working a lot with FreeRTOS and Embedded Linux.
Right now I'm focused on compiler technology, computer architecture and an academic project regarding computer vision, AI and hardware acceleration in an FPGA.

For the Google Summer of Code, the ideas that I'm very interested in are: 'port FreeRTOS to Portenta' and 'write MicroPython examples and tools for Portenta'.

I'm looking forward to solving some bugs and further improve my skills and knowledge.

**Comment by alranel** [comment]
Welcome @djdo! Looking forward. Given your background I'd suggest to go with the FreeRTOS project. It's not easy but it's definitely doable and you will learn a lot. Also, many people would benefit from your work. Make sure you read the application guide contained in this repository as it explains how to write a good project proposal and feel free to use this page to ask questions.
