### ISSUE TITLE
Inquiry abut Project 1 : Write an analyzer for Arduino libraries

### ISSUE THREAD

**Issue by HitbyUoft** [arduino/summer-of-code#74]
How many aspects are we looking to check, you guys mentioned some examples but if you could break down the aspects we want to check foe each library ??

**Comment by HitbyUoft** [comment]
Everyone is giving their resume so I will too.
I am Aryan Bansal, first year electrical engineer at University of Toronto Canada. I have already done a advance level course in c and have great knowledge of C Language.
I have also been to Robotics Nationals in FTC that uses Aurdino as its Brain. I am beginner tough. I don't have much knowledge of C++ but I will learn necessary code for this project if I am Accepted . I am a Hard worked and committed individual.

**Comment by alranel** [comment]
Hello @HitbyUoft, the ideas page includes some [examples](https://github.com/arduino/summer-of-code/blob/master/ideas.md#idea-write-an-analyzer-for-arduino-libraries) of things we might want to check. Feel free to add any further ideas in your proposal. The listed examples are already quite complex so I suggest to focus on them.
