### ISSUE TITLE
Gsoc2020: port FreeRTOS to Portenta

### ISSUE THREAD

**Issue by MRNIU** [arduino/summer-of-code#76]
Hello, everyone!
I'm interested in the work of porting the FreeRTOS to Portenta. I have experience in developing operating systems and using rtos. And I have written the compatibility layer of Arduino for AliOS-Things.

This is my operating system work, it is not finished yet: [SimpleKernel](https://github.com/MRNIU/SimpleKernel)
And this is the Arduino compatible layer I wrote for AliOS-Things: [AliOS-Things_ArduinoFramework](https://github.com/MRNIU/AliOS-Things)

This is a challenging job for me, and I will write my work plan in as much detail as possible in the proposal.

There is a problem. The [Application Instructions](https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md#during-the-application-phase-february-20th---march-31st) requires a bug to be solved. Is there a requirement for the difficulty of this bug?

Think you!

**Comment by alranel** [comment]
@MRNIU looking forward to receiving your proposal. Freel free to use this page to ask any questions. There's no complexity requirement for the bug to solve.

**Comment by MRNIU** [comment]
@alranel hi, I have summit a pr: https://github.com/arduino-libraries/Keyboard/pull/35

**Comment by MRNIU** [comment]
@alranel I have shared my draft but there is no comments until now. What should I do to get a feedback?

**Comment by MRNIU** [comment]
@alranel 
Hello, I am honored to be able to participate in this year's event. Is there any contact information to discuss?

**Comment by ashpande** [comment]
Hey, congratulations on being accepted. I'm the other student that Arduino selected. All the best for your project!

**Comment by MRNIU** [comment]
@AshutoshPandey123456 
Same to you.
Maybe we can exchange telegram?

**Comment by ashpande** [comment]
Yeah sure!

I'm Ashu_tosh_Pandey (username) on Telegram.

**Comment by MRNIU** [comment]
I am Zone233.
Looking forward to your message.

在 2020年5月23日，13:43，Ashutosh Pandey <notifications@github.com> 写道：

﻿

Yeah sure!

I'm Ashu_tosh_Pandey (username) on Telegram.
