### ISSUE TITLE
Write MicroPython examples and tools for Portenta - Dushyant Panchal

### ISSUE THREAD

**Issue by dushyant18033** [arduino/summer-of-code#77]
Hi,
I am Dushyant Panchal, a second-year B.Tech Computer Science and Engineering student from Indraprastha Institute of Information Technology, Delhi and I am looking forward to contributing to the betterment of Arduino and Portenta community.

The project I'm very much interested in and would like to give my best contribution to for GSOC 2020 is "Writing MicroPython examples and tools for Portenta".

I have more than 3 years of experience working with Arduino UNO and have worked on many interactive projects including an Arduino-based firmware for quadcopter flight control (still under development), a self-balancing bot, a HelpCap (a cap-like device that can emulate mouse events on specific head movements connected to the PC via BlueTooth) which was also selected among the top projects in my college course project showcase. I have also worked a little bit with nodeMCU (both via MicroPython and Arduino IDE). Hence I assure you that this is going to be more of a passion for me than work.

I just learned about this Arduino Portenta H7 to be released in March 2020 and wish to have a hands-on experience with this powerful board.

Looking forward to a positive response.

Thanks and Regards
dushyant18033@iiitd.ac.in

**Comment by dushyant18033** [comment]
@alranel As you had asked I opened a separate issue for a private communication channel.

When will the MicroPython documentation for Portenta be available?

I have submitted the draft proposal on the GSoC portal and waiting for the review.

Thanks

**Comment by dushyant18033** [comment]
Also, will the documentation for MicroPython in Portenta also be released?

**Comment by alranel** [comment]
Thank you @dushyant18033. The release for the documentation and code for Portenta is going to happen in the next few weeks.

**Comment by dushyant18033** [comment]
I would like some mentor to review my GSoC proposal draft submitted on the gsoc portal to verify if it is sufficient and suggest changes if needed as the final proposal submission is just a week ahead.
Thanks

**Comment by dushyant18033** [comment]
Also, I had made a simple project where you could control an RGB LED through a TCP socket over wifi by sending some specific commands from laptop or a phone in the same network as the device. This was based on micropython and esp8266. I can share the code if asked for. In addition to what all I have proposed in my proposal, I would like to port this remotely controlled RGB light to Portenta. If if time permits I would also like to make a self balancing bot using micropython on Portenta. Additionally I will document these on the project hub. 

Looking forward to be a part of your community 

Thanks and Regards.

**Comment by dushyant18033** [comment]
Hi, I am eagerly waiting for the Arduino Portenta MicroPython documentation to be released. I even checked MicroPython's official website but there is no mention of Portenta documentation yet. When is it going to be publicly accessible? Or is it the same as the one for pyboard since both pyboard and Portenta run on SMT32?

Thanks
