### ISSUE TITLE
GSoc-2020: Libraries for Arduino and Portenta

### ISSUE THREAD

**Issue by santhoshmathavan** [arduino/summer-of-code#78]
Hey all,
This is Santhosmathavan K currently pursuing my M.Sc Software systems (Integrated program). I am interested in developing Libraries for Arduino and Portenta boards. I completed a 6 months internship as a Junior Firmware developer and having good experience in working with Arduino UNO, MEGA boards. Interested in developing serial communication examples for Arduino boards to other developement boards. Written functionalities for Adafruint Fingerprint Library using C++.
Created a Serial Communication between arduino mega and nrf52832 board through ATCOMMANDS.
Looking forward to work with you .

**Comment by alranel** [comment]
Thank you @SandyHub99. Make sure you read the application guide that explains how to write a good project proposal.
