### ISSUE TITLE
Writing examples for library 

### ISSUE THREAD

**Issue by hailcpy** [arduino/summer-of-code#79]
Hello, i am from india. I have been working with arduino and other development boards(stm32,esp32) supported by arduino ide for the past 4-5 years. It had helped me and others electronic hobbyists like me. I wanted to contribute something to this community to thank them. So i have decided to write examples for some arduino libraries which do not have sufficient examples to provide information about all the functions of the library. I have picked up some libraries and working on it.

**Comment by hailcpy** [comment]
i have decided to write examples and also upload tutorial for the following libraries -
1) Wifi library - i have written one example to handle multiple clients, to control servo   and want to 
        write more some examples for the library 
        https://github.com/arduino-libraries/WiFi
2)Servo - Since all servos are not equal and they require little different duration of maximum and 
        minimum pulses. So i want to write an example to control the duration of maximum and 
        minimum pulse sent to a servo using potentiometer(to change duration) and button(to set 
        change for either maximum pulse or minimum pulse).
        another example i want to write is to control servo position using serial monitor.
        https://github.com/arduino-libraries/Servo
3)GSM library-controlling led using messages  
        https://github.com/arduino-libraries/GSM
4)CapacitiveSensor library - it needs an example to create a keyboard and some more examples
        https://github.com/arduino-libraries/CapacitiveSensor/tree/master/examples/CapacitiveSensorSketch
5)Keyboard- an example to create notes using buttons buzzer and arduino, an example to use 
        shortcuts on keyboard and an example such that same keys can be used for multiple functions   
        like modifier keys.
        https://github.com/arduino-libraries/Keyboard
6)Mouse-an example showing to use joystick module with arduino boards like the pro micro, 
        leonardo to act as mouse and also upload a tutorial for the same.
        https://github.com/arduino-libraries/Mouse
7)ArduinoBLE- examples like controlling servo, uploading code over bluetooth using bluino app
        https://github.com/arduino-libraries/ArduinoBLE
Hey @alranel @per1234  what do you think about these examples. I have enough free time during the entire GSOC so i could really contribute to the Arduino community.

**Comment by alranel** [comment]
Hello @hailcpy. Those ideas sound nice! Go ahead with writing your proposal following the application guide in this repository!

**Comment by hailcpy** [comment]
hey @alranel  i have submitted the draft please provide feedback.
