### ISSUE TITLE
libraries Examples

### ISSUE THREAD

**Issue by mash197** [arduino/summer-of-code#80]
My name is Mohamed Lotfy, i'm a computer engineering student and an Arduino user. I'm a finalist in the CodeGeist 2018 hackathon and i have previous experiences one of then is being an intern at Microsoft advanced technology reasearch lab.

Here is a sample of my contribution to the Servo library : 
https://github.com/arduino-libraries/Servo/pull/40#issue-387322116

And i will explain precisely my approach and my plan for writing the examples through out the program period in my submitted proposal.

**Comment by alranel** [comment]
Hello @mash197, and welcome. Thank you for the contribution. Make sure you read the application guide in this repository and that you detail the examples you intend to read in your project proposal.

**Comment by mash197** [comment]
Hello @alranel , i have already read the application guide in the repository and followed it to create a detailed proposal including al the details about the libraries that i want to work on, it would be very helpful if i can get feedback on the proposal, i submitted the link and proof of enrolment to GSOC website.
