### ISSUE TITLE
GSoC 2020 - Arunaabh Singh

### ISSUE THREAD

**Issue by arun2201** [arduino/summer-of-code#81]
Greetings!
My name is Aruaabh Singh, I am a first-year Electronics and Instrumentation undergraduate at Birla Institute of Technology and Science, Pilani.  
I am interested in the Idea: **Write examples for official libraries**. 
I have experience in both high and low levels of programming languages like; JAVA, Python, and C
I have also worked with Arduino Uno/Mega, ATMEL/AVR microcontrollers.
My goal is to present the library in a most user-friendly way so as to facilitate users to easily use the library and get a feel as to how it works with the help of examples and projects (with documentation). I believe if one can understand the library and its functionalities well he/she can user-friendly projects.
Very excited to join Arduino Community!!
Thank you.

**Comment by pr3dat0r2201** [comment]
Hello,
I have changed the PWM frequency for M3 and M4 (controlled by the D21).
https://github.com/arduino-libraries/MKRMotorCarrier/pull/19#issue-387791302
Thanks.

**Comment by alranel** [comment]
Welcome @pr3dat0r2201! Just a reminder: make sure you have read the application guide contained in this repository that explains how to write a good project proposal.

**Comment by arun2201** [comment]
Thank you for the help @alranel 
could you please share your mail so that I can send my draft for review before submitting the final proposal.
