### ISSUE TITLE
[GSoC2020]Porting FreeRTOS to Portenta and Writting Project Templates (proposal wait feedback)

### ISSUE THREAD

**Issue by Derekduke** [arduino/summer-of-code#83]
My name is derek deng, and I come from China. I am a postgraduate student at the Key Laboratory of Mobile Edge Computing at Xidian University. My current research direction is embedded distributed machine learning. I am also a 5-year Arduino fan. In the Arduino student organizations founded at my undergraduate level, I teach students to make robots using Arduino development boards and sensors. At present, more than 100 members have joined.

I am very familiar with the underlying source code of Caffe. I am skilled in the use of C / C ++, understand the Linux kernel and IO, and attach great importance to memory control and power consumption in embedded devices. I have participated in the Intel Embedded Design Competition and Xilinx Low Power Target Detection Contest (SDC). I have the ability and experience to deploy machine learning algorithms on Intel Up2 and Xilinx Zynq. I also used STM32 to develop distributed for the company Calculated actual project.

I learned that Portenta is a high-performance computing card that solves AI problems. I'm afraid I can't wait to participate in the open source community to add new machine learning libraries or lightweight deep learning frameworks for Arduino, and add pictures or speech AI. Write tutorials to make it easier for more people to deploy edge AI using Arduino.
My question is:
1. According to the options on the Ideas List, there is no AI task. If I submit a proposal, can I describe ideas that are not on the Ideas List? Or do I have to choose the task requested on the Ideas List?
2. Based on my personal experience and ideas, is it eligible to apply? 
    Hope to get suggestions, thanks!

**Comment by alranel** [comment]
Hello @Derekduke, feel free to propose a project which is not on the list but keep in mind that we might not have a mentor for that particular task.

**Comment by ToSeven** [comment]
Can Arduino afford the work about AI calculation?

**Comment by Derekduke** [comment]
> Can Arduino afford the work about AI calculation?


I have deployed a neural network on STM32 for image classification. For the H747 of Arduino's Portenta, it is easier to implement a network that only performs forward propagation.As for the performance, I don’t know until I get the board.

**Comment by Derekduke** [comment]
> Hello @Derekduke, feel free to propose a project which is not on the list but keep in mind that we might not have a mentor for that particular task.

Thanks for your answer. I will try to focus on the ideas on the ideas list, such as describing some experiences and details of FreeRTOS porting. 
1.In which way is more appropriate about "proof of experience with the low level programming required for such task" as the ideas list description?Maybe show the porting source code of different boards I did before?
2.May I please put the github link of my proposal draft directly below this issue?

**Comment by alranel** [comment]
I'll answer your questions:

1. Showing code you have already written for low level programming, such as ports for various boards, is a good way to show proof of experience.
2. Of course, feel free to use this page to ask any question about your proposal.

**Comment by Derekduke** [comment]
Thanks for your guidance@alranel .
I uploaded part of the code that I used to develop and related to the underlying development. Please refer to my github:
- https://github.com/Derekduke

This is the proposal draft I have written.Although it has been submitted to the Gsoc platform, there is no feedback yet.So I really hope to get some suggestions：
《Porting FreeRTOS to Portenta and Writting Project Templates》
- https://drive.google.com/file/d/1fm-hIehkfWrZYpUHvsGyGPyRfEpQfQ6r/view?usp=sharing

Very grateful！
 dkeji627@gmail.com
