### ISSUE TITLE
Creating examples and tutorials for Arduino libraries

### ISSUE THREAD

**Issue by shahkairav** [arduino/summer-of-code#84]
Hi,

I am a second year undergraduate of Computer Science at Indian Institute of Technology, Madras. I would like to create new examples and tutorials for the existing libraries that are so widely used by the Arduino users. I hope that these examples can alleviate the struggles of many. Please let me know if I can start working on this project. Also, please let me know what is expected of such a project. Thanks.

**Comment by alranel** [comment]
Hello @FerociousYogi, make sure you have read the application guide contained in this repository that explains how to write a good project proposal.

**Comment by shahkairav** [comment]
I have! Shall I start working on this then? Please guide me so that I can begin. Thanks a lot.
