### ISSUE TITLE
GSoC '20 Introduction: Porting FreeRTOS to Portenta

### ISSUE THREAD

**Issue by zainamir98** [arduino/summer-of-code#85]
Hi everyone!

My name is Zain Amir Zaman and I am a 3rd year electrical engineering student at the National University of Science and Technology (NUST) in Pakistan. While reading the ideas list I came across a proposal to port FreeRTOS to Portenta, which piqued my interest as I have ample knowledge and experience on working with low-level hardware and programming in C. I hope to work with you in the near future!

**Comment by alranel** [comment]
Hello @zainamir98, and welcome! Just a reminder: make sure you have read the application guide in this repository that explains how to write a good project proposal, and feel free to use this page to ask any questions.
