### ISSUE TITLE
GSoC 2020! Writing Examples For Arduino Libraries

### ISSUE THREAD

**Issue by Arsh0508** [arduino/summer-of-code#86]
Hi everyone!

I am Arsh Mahajan, a third year computer science undergraduate student at Indian Institute of Technology Patna (IIT Patna), India. 
I came across the project idea for writing examples for arduino libraries without much examples. Honestly I believe this is a great idea and needs to be implemented as sample codes are a big help to beginners and even experienced users who are new to the library or are facing some doubts.
I have worked on quite a few arduino projects throughout my three year journey at college and it always amazes me how well arduino integrates software and hardware.
That said, all the examples and arduino itself has helped me a lot in my projects over all the years and now I would very much love to contribute back to the community and make it even better for others who have joined or are yet to join the arduino family.
As of my experience I have good enough experience in C, C++, Arduino which would help me towards the project and I am more than willing to learn anything new that I might have to learn whilst on this project.
Hoping to work with the community soon :)

**Comment by ausaafnabi** [comment]
Should I consider writing examples for core libraries only?

**Comment by alranel** [comment]
Hello @Arsh0508, and welcome to the community. Just a reminder: make sure you read and follow the application guide in this repository, which explains how to write a good project proposal.
