### ISSUE TITLE
GSoC 2020 - Ashutosh Sharma

### ISSUE THREAD

**Issue by ashutoshshrm529** [arduino/summer-of-code#88]
Hello Everyone,
I'm Ashutosh Sharma, a Computer Science Undergrad from BITS Pilani, Rajasthan. 
I commonly work on arduino projects and have been doing so for the past 3-4 years. I have experience in machine learning and have made arduino based projects such as a Micromouse ( https://github.com/BitsRobocon/MicroMouse_2020 ), efficient line followers and currently am working (with my robotics club - ROBOCON BITSP https://teamroboconbitspilani.github.io ) on an autonomous quadruped which is to navigate an environment and do certain tasks (push items, or deliver boxes).

I also am a Full-Stack web developer and a hobbyist Graphics Designer.

I have been particularly in interested in participating in open source communities, specially this one, given that most of my work revolves around it. I wish to be a productive and helpful member of this community and have a good experience in doing so.

I have ample programming experience in C, C++, Go and Python and hope to be a contributor to the new Portenta board particularly writing MicroPython examples and tools for Portenta and JerryScript (JavaScript) examples and tools for Portenta since these are features which will expand the arduino environment and will particularly be useful for my robotics work. I hope to spend my GSoC period working on this project and to be a helpful open source contributor to this community.

**Comment by ashutoshshrm529** [comment]
As asked in the how-to-apply section, This is a link to the Pull Requests I recently submitted 
to the ArduinoGraphics Library 
 - https://github.com/arduino-libraries/ArduinoGraphics/pull/11 
 - https://github.com/arduino-libraries/ArduinoGraphics/pull/15 

to the Arduino_MKRGPS Library
 - https://github.com/arduino-libraries/Arduino_MKRGPS/pull/5

to the Arduino MKRTHERM Library
 - https://github.com/arduino-libraries/Arduino_MKRTHERM/pull/3

Thank You

**Comment by ashutoshshrm529** [comment]
Hello @alranel @tigoe @per1234 ,

I have submitted my draft proposal through the GSoC dashboard. Could you all please review it and suggest changes.

Thank You

**Comment by alranel** [comment]
Hello @ashutoshshrm529, thank you for submitting the proposal. We will do our best to review it, although we are overwhelmed with proposals and we're doing our best!
