### ISSUE TITLE
GSoC 2020 - Examples for how many libraries

### ISSUE THREAD

**Issue by zaidMughal** [arduino/summer-of-code#89]
I'm Zaid from NUST. I have been working on arduino hobby projects since 2016. Now, after gaining sufficient experience, I want to write examples to help my fellow hobbyists. 
I want to ask that at least how many libraries should we write examples of?
Thanking you in advance.

**Comment by zaidMughal** [comment]
I fixed issue 6 of liquid Crystal library.Please review and mearge it.:)
https://github.com/arduino-libraries/LiquidCrystal/pull/32

**Comment by alranel** [comment]
Hello @zaidMughal, welcome and thank you for your contribution. The number of libraries depends on the complexity of the examples. On average, you might want to work on 3 to 5 libraries, provided you create also some advanced examples and maybe also a physical prototype.
