### ISSUE TITLE
How should one submit examples for portenta board when its not locally available for purchase?

### ISSUE THREAD

**Issue by pra-dan** [arduino/summer-of-code#9]
Hello, 
I am looking forward to working with the amazing Arduino open-source community for GSoC 2020. I read about the portenta board and was pretty amazed by its specifications and modern design. I am waiting eagerly to use it to deploy tiny ML models. 
But, how should I experiment with it and submit examples for it when I can't avail it right now?

**Comment by derekdunes** [comment]
They said they will send you a free board if you get selected for the gsoc program "Note: accepted students will be sent a free Portenta board."

**Comment by ghost** [comment]
Hey Prashant! 
Since you live in Dehradun, I would suggest you to purchase it from a foreign website and ship it to India. Since, sellers in India are currently not supplying the Portents Board.

**Comment by pra-dan** [comment]
@derekdunes but we need to start contributing before the selection starts and the boards will only be provided after that.
_Win at digging and win a shovel_

**Comment by pra-dan** [comment]
I found this: 
> The Portenta H7 will be ready for shipment approximately at the end of March 2020.

**Comment by derekdunes** [comment]
@PrashantDandriyal I think it's up to the organization to state how developers get the boards and start contributing.

**Comment by pra-dan** [comment]
Yeah exactly @derekdunes.
I wonder when can we expect responses from the organizers?

**Comment by thekunalsaini** [comment]
Hello all,
I am Kunal Saini from Kurukshetra, Haryana, India. I am a 3rd-year undergraduate student. I have worked on Arduino from very beginning i.e. from LED blinking to automation using IoT with IBM watson and building a mobile and robots using Arduino.
I have made lots of example .
Thank you,
Kunal Saini


Looking forward to becoming part of the Arduino Community and making contributions

**Comment by vedrocks15** [comment]
Is there any online platform or simulator available to run the portenta h7 board ( like Proteus or circuito.io) ?

**Comment by alranel** [comment]
@PrashantDandriyal the Portenta board will be sent to the selected students. Since it's not currently available, you can still provide your contributions to one of the projects listed at https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md#during-the-application-phase-february-20th---march-31st
