### ISSUE TITLE
GSOC: port FreeRTOS to Portenta

### ISSUE THREAD

**Issue by pankaj599** [arduino/summer-of-code#90]
Hello Everyone,
This is Pankaj Kumar Vijayvergiya, currently pursuing  3rd year in Electronics and Communication Engineering, NIT Surat. I am working on the arduino projects for the past 3 years and currently working on Rover for the Indian Rover Challenge (https://pankaj599.github.io/rover/) 
I have knowledge in Embedded system and hardware and knows programming languages like C, C++, python. Apart from this I am a frontend web developer. 
I have been interested in participating in open source community’s project and wants to contribute in RTOS to Portenta board.  I have ample knowledge and experience on working with low-level hardware and programming in C and looking to work with you.
This is my Github repositories: https://github.com/pankaj599
Thanks.

**Comment by alranel** [comment]
Hello @pankaj599, and welcome. Porting FreeRTOS is an advanced challenge, so make sure you study the topic well. Also, make sure you read the application guide contained in this repository, that explains how to write a good project proposal.
