### ISSUE TITLE
Writing MicroPython/JerryScript examples, tools and prototypes for Portenta with tutorials in ProjectHub

### ISSUE THREAD

**Issue by SpookyCorgi** [arduino/summer-of-code#91]
**Who am I?**
Hi my name is Lee, Cheng-Chi and I’m a Mechanical Engineering major, CS minor student at National Taiwan University and I have been in a robotic lab for 1.5 years. I‘ve been experienced with Arduino and used it for the past four years. Projects I’ve done with Arduino are “Propeller-powered line tracing vehicle”, “Self-lift cable climbing machine” etc. Thus I’m proficient in topics of motor(servo, stepped and brushless), remote/non-remote control(Bluetooth, USB), control system(PWM, PID) and so on. Minor in CS, I’m also familiar with python and JavaScript. 
I’m really excited about how Portenta can change the way existing Arduino libraries works and what new potential it has. So I want to work on the project of writing MicroPython/JerryScript example tools for Portenta. As a ME student, my interest is in the practical use of all kinds of functions and building hardware prototypes.

**Proposals**
Basic robotic vehicle
A robotic vehicle with the use of servo motor controlling wheels. (Shape or form not limited. Don’t need to be a car.) A typical Arduino project for those who love to DIY. I also can design CAD files for people to 3D print themselves. I've got 3D printing and laser cutting resources so I can build and test prototypes and write tutorials.
 
More functions for the robot! Sensors!
Adding IR sensors, ultrasonic sensors to the robot and do all kinds of cool stuff.

Connectivity
One of the most exciting of Portenta for me is the built-in Bluetooth and WiFi. As someone who is experienced in hc-05/06 Bluetooth module. I know debugging those external modules is a pain. With those functions built-in, we can remote control the robot easily or display data from the sensor in realtime.
	
More to come
Those are just part of the projects I thought of. There are still many features I want to test and build such as Graphic display or make use of the powerful dual-core.

**Comment by SpookyCorgi** [comment]
Hi, I have sent a draft on 3/21. If possible, any opinion or suggestion would be helpful. Thank you.

**Comment by alranel** [comment]
Thank you @ScarySheep, for sending a proposal! We will do our best to try to review it before the deadline. We are overwhelmed with submissions but we'll try.
