### ISSUE TITLE
 write JerryScript (JavaScript) examples and tools for Portenta

### ISSUE THREAD

**Issue by therealbigzeez** [arduino/summer-of-code#92]
Hello,
I am Azeez Lukman and i am happy to be here, 3rd year Computer Science major from Lagos state university, Nigeria. I have experience creating arduino projects since 2016 and i taken many tutorial courses and documented my projects on instructables.

I have professional experience in JavaScript and C++, i also have experience using IoT , running node.js on arduino board with johnny-five. I recently gained interest in Samsung's JerryScript and I am happy to use it as well. 

For this summer of code, I would like to write  write JerryScript (JavaScript) examples and tools for Portenta and i would be more than glad to help grow the community.

Best wishes,

Lukman

**Comment by therealbigzeez** [comment]
Currently the biggest problem that JerryScript has is that its **documentation** is non-existent. All you have is the code and no clue on how to use it on any given platform, making the learning curve steep.

Along side with my examples i also plan to write a good and beginner friendly documentation for JerryScript as  other developers would find it helpful and handy to write JerryScript  on the Portenta board and also grow the community.

I want to know if i can create the documentation as part of my project with arduino for this summer of code.

**Comment by AbhinavMir** [comment]
Hi @Robogeek95 , for basic documentation you can refer to https://github.com/jerryscript-project/jerryscript .
All the best!

**Comment by alranel** [comment]
Hello @Robogeek95, and welcome. The Summer of Code is mostly about coding rather than about writing documentation, but of course writing documentation as part of a coding project is welcome. And yes, you are right about noting that there's not much documentation about JerryScript, so the challenge is also about learning about how to make it run on a new board based on the existing documentation about other already supported boards.

**Comment by therealbigzeez** [comment]
Thanks @alranel, i understand, i'll still provide a friendly documentation for every of my code examples based on the already existing documentations, I do not want other developers to find it so hard using my examples as the current documentations feels, makes it fun while learning something new.

**Comment by therealbigzeez** [comment]
Please Milestone

> Hi @Robogeek95 , for basic documentation you can refer to https://github.com/jerryscript-project/jerryscript .
> All the best!

Thanks @AbhinavMir, already checked that out, but ill be glad to have you refer me to some other resources, that might really help out

**Comment by AbhinavMir** [comment]
@Robogeek95 I am working on a Repo named JerryScriptForHumans. 
Github.com/abhinavmir/jerryscriptforhumans

**Comment by therealbigzeez** [comment]
@AbhinavMir , Thats cool! Just Checked the repo but its still empty, can you provide a few details on JerryScriptForHumans, i am really interested.

**Comment by AbhinavMir** [comment]
@Robogeek95 I will be adding post-31st. The pandemic wildly affected my schedule 😥.
