### ISSUE TITLE
GSoC - Introduce Myself

### ISSUE THREAD

**Issue by WhymustIhaveaname** [arduino/summer-of-code#93]
I am Sun Youran, a senior student at Peking University majoring in Physics. 

I have programmed with Arduino for 3 years. I did some great works with Arduino, including a fingerprint lock, an air condition monitor and many small projects. C and Python are my most familiar languages. I also have essential knowledge in assembly, operating system, computer network, database, and many other programming languages. I am good at writing fast and well-documented codes.

I can write examples for official libraries, or write MicroPython examples and tools for Portenta, or port FreeRTOS to Portenta. It is important that I can do something for Arduino, not what to do, as I think I am capable of all your ideas.

Reply to me if you are interested and then I will upload a proposal.

**Comment by ayan-biswas0412** [comment]
I am Ayan Biswas , a undergrad at Jadavpur University , Kolkata majoring in Electronics and Telecommunication Engineering .
As per my course curricula I have done several arduino projects ranging from opencv based trafiic signal detection car , basic line follower , bluetooth module based car and a smart door lock system using NFC cards etc. My comfortable programming languages are  C/C++ , pyhton and also i posses knowledge of maintaining database (MySQL, POSTGREsql etc )and i also comfortable in web developing . 

I can work in the areas of writing examples for official libraries, or writing MicroPython examples and tools for Portenta, or port FreeRTOS to Portenta , again as my major subject is fully related to this project so i want to do this as i think i am capable for this ,

Reply me if you are interested after that i will uload my complete proposal for GSOC 2020

Also see my profiles : 
Website :  https://ayan-portfolio.firebaseapp.com/ 
Linkedin : https://www.linkedin.com/in/ayanbiswas-juetceug/
Blog : https://ayanbiswas291395828.wordpress.com/
Medium : https://medium.com/@ayanbiswas184
                                                                             Thanking you,
I will be highly obliged if you want me in for this project .


Regards from, 
 
**AYAN BISWAS,**
UG Student (2019-23 Batch) at 
**Department of Electronics and Telecommunication Engineering
Faculty of Engineering Technology
Jadavpur University**

**Comment by alranel** [comment]
Hello @WhymustIhaveaname. You should choose a project to work on, and prepare your proposal by following the application guide you'll find in this repository.
