### ISSUE TITLE
GSoC: Add self introduction

### ISSUE THREAD

**Issue by Qs-F** [arduino/summer-of-code#94]
Hi, Arduino team, 

I'm Fumi TAKEUCHI, a Japanese Senior Undergraduate.

I want to work on `arduino-cli`, for the `network discovery functionality`.  
Maybe, it seems what you need is some kind of `Bonjour`?  
By reading [this issue](https://github.com/arduino/arduino-cli/issues/69), it looks network lookup (like https://github.com/brutella/dnssd 's LookupType or https://github.com/oleksandr/bonjour 's Lookup) is missed.

Although I do not have any Arduino devices, I have written Go since v1.4 was released, and I like to work on middle to low level layers.

Best regards,  
Fumi

**Comment by rsora** [comment]
Hi @Qs-F , I'm Roberto from the arduino-cli core developer team,
First of all thanks for your interest in contributing to the arduino-cli project, willing and experienced Golang devs are always welcome in the arduino-cli contributors family! :smiley_cat: 

We had an internal discussion in the arduino-cli team and decided to propose a new activity on the CLI for the GSOC (see https://github.com/arduino/summer-of-code/pull/127) replacing the "network discovery" activity. 
We think that implementing the "external programmers" feature will provide great value to our community.

Feel free to check the relevant issue (https://github.com/arduino/arduino-cli/issues/27) and decide freely if you still want to contribute to the arduino-cli project. 
If you decide to go on in implementing the "external programmers" feature, please close this issue and open a new one, including  "_**arduino-cli external programmers feature**_" in the title, we will start to help you in your new issue.

I think also this feature implementation could be a good one for you, as you should be able to test the functionality you will implement without the need for an Arduino board in the short term.

Cheers from the arduino-cli team :+1:
