### ISSUE TITLE
New Project Proposal: First Person View (FPV) and Image Detection with Portenta

### ISSUE THREAD

**Issue by achen173** [arduino/summer-of-code#96]
I’d Like to propose a new project for the upcoming GSoC, 2020. This project will be focused on Image Detection through a First-Person View Camera. Specifically, this project will utilize Portenta computation powers to run a pretrained neural network model (open source) for image detection in real time. Then, by using the onboard wireless module or by physically adding a transmitter (if need be), we can transmit the image to external device such as a VR headset or phone. Development of libraries would be important to make this application user friendly and versatile.

This project will be unique because:
1.	The Portenta will be an attachable module on any remote-controlled electronics such as a store-bought RC car or a self-build drone. This module will be transferable since it does not have any dependence with the existing application. Attach it to anything and you will be able to control it through first-person view; hence reusable. Some store bough drones come with camera view, but it is built within (not removable).
2.	Store-bought drones, for example, often do not have image detection abilities because they lack the hardware. Even if they do, it is rare that you will be able to use an image detection technique of your choosing. With Portenta, you can choose from a wide variety of image detection methods (or program it yourself) and not worry about the computational powers.

Example of Result (hopefully):
![CaptureGoogle](https://user-images.githubusercontent.com/54816128/76925203-045d2480-68af-11ea-95a4-98ac21fff415.JPG)

This is a new idea but also overlaps with the existing idea of "_Idea: write MicroPython examples and tools for Portenta_". This is a high-level view of the plan and I would like to know what you guys think of it?

Thank you, achen173

**Comment by alranel** [comment]
Hello @achen173! That sounds like an ambitious project, but if you think you can do it, well, green light - go ahead and write your proposal. Make sure it's well detailed.
