### ISSUE TITLE
Feedback Request

### ISSUE THREAD

**Issue by kanishchugh** [arduino/summer-of-code#97]
Hello sir/madam.
I would request you for feedback for my proposal/application.
if possible please share feedback on kanichugh2001@gmail.com
The link to my proposal is down below:-
https://docs.google.com/document/d/1grFWisW2rSTzRclaoya1UYtioeZIfSdsnN-OUkgedqc/edit?usp=sharing

**Comment by alranel** [comment]
Thank you @kanishchugh, that looks good! (Keep in mind we are receiving a lot of applications, so if you can improve this with more details it may have better chances)

**Comment by kanishchugh** [comment]
Greetings @alranel, thank you for your feedback. I have made certain substantial changes as suggested in the proposal and would really like you to review it again. Thanks again for your valuable feedback.

**Comment by kanishchugh** [comment]
Greetings @alranel, was just getting familiar with the pro IDE and i had a query that till when will the support for Portenta will be released? and as well as the documentation. no hurries, just really exited about this project ;)
