### ISSUE TITLE
Write Examples for official Libraries - Practical Approach

### ISSUE THREAD

**Issue by Inv3nt0r1** [arduino/summer-of-code#98]
### Hello,
My name is Durgesh Pachghare, a Computer Engineering Undergraduate from India. Arduino was the thing from which I started my learning and experiments in Robotics. I have 5 years of experience working with various Arduino boards, a large variety of sensors and actuators. I lead the robotics club in my college and I am a Technical Lead of Robotics Teams which makes complex robots for various robotics competitions. I have proficiency in Arduino, C, C++, and Java Programming Languages. 

### Motivation
Arduino is a member of my daily experiments. I learned Arduino completely from the examples of Libraries present in the IDE and using that I used to write my own programs and try it. After practicing, I was able to write advance level code with Arduino integrating multiple sensors, actuators, and various devices. Examples play a very important role in learning Arduino and trying new things. So, I want to make contributions that will be really helpful for the entire community of makers.

### Practical Approach
My approach aims at providing many examples and examples integrating multiple components. Many projects require integration of multiple components, so if we give examples in that approach, more people will understand and will try given examples and learn more. A detailed explanation will be in the Proposal. 

I will update this thread once I submit my draft. 

Thank you.
Regards,
Durgesh.

**Comment by Inv3nt0r1** [comment]
Sample PRs Submitted:
https://github.com/arduino-libraries/Arduino_LSM9DS1/pull/8
https://github.com/arduino-libraries/Servo/pull/43

**Comment by alranel** [comment]
Welcome @Inv3nt0r1. Make sure you read the application guide in this repository which explains how to write a good project proposal.

**Comment by Inv3nt0r1** [comment]
Thank you so much for the reply. 
I am working on Proposal, I will submit it for review tomorrow. 
I am ensuring it to be as detailed as possible.

**Comment by Inv3nt0r1** [comment]
Hello @alranel @per1234,
I have submitted my draft on the GSOC portal. Kindly review it and tell me changes/suggestions/additions if any. 
Thank you.

**Comment by Inv3nt0r1** [comment]
Is there any specific reason why the Arduino IDE has more examples than the actual library Repo?

@per1234

**Comment by per1234** [comment]
Would you mind providing some more details @Inv3nt0r1. Which library repo are you referring to? What is the exact menu path in the Arduino IDE where you are seeing the additional examples?

**Comment by Inv3nt0r1** [comment]
I apologize for not giving full details.

For example, [Keyboard Library](https://github.com/arduino-libraries/Keyboard) have only [1 example](https://github.com/arduino-libraries/Keyboard/tree/master/examples) in Github Repository i.e. Seria.ino. 

But in IDE, under File > Examples > USB > Keyboard, there are 4 examples listed namely
* KeyboardLogout
* KeyboardMessage
* KeyboardReprogram
* KeyboardSerial

Also, the [reference link of Keyboard Library](https://www.arduino.cc/reference/en/language/functions/usb/keyboard/) has a description of all the examples listed in IDE.

Same is with [Mouse Library](https://github.com/arduino-libraries/Mouse) which does not contain any example at all in Github Repo, but it got 2 examples in the same path in Arduino IDE.

**Comment by per1234** [comment]
Those examples are bundled with the Arduino IDE:
https://github.com/arduino/Arduino/tree/master/build/shared/examples/09.USB

I think the reason is because years ago the Keyboard and Mouse libraries were part of the core library. When they were made into separate libraries, the examples were left in their original location.

There are proposals to move those examples to the library repositories:
- https://github.com/arduino-libraries/Keyboard/pull/30
- https://github.com/arduino-libraries/Keyboard/pull/32
- https://github.com/arduino-libraries/Mouse/pull/12
- https://github.com/arduino-libraries/Mouse/pull/13
- https://github.com/arduino-libraries/Mouse/pull/15

**Comment by Inv3nt0r1** [comment]
> Those examples are bundled with the Arduino IDE:
> https://github.com/arduino/Arduino/tree/master/build/shared/examples/09.USB
> 
> I think the reason is because years ago the Keyboard and Mouse libraries were part of the core library. When they were made into separate libraries, the examples were left in their original location.
> 
> There are proposals to move those examples to the library repositories:
> 
> * [arduino-libraries/Keyboard#30](https://github.com/arduino-libraries/Keyboard/pull/30)
> * [arduino-libraries/Keyboard#32](https://github.com/arduino-libraries/Keyboard/pull/32)
> * [arduino-libraries/Mouse#12](https://github.com/arduino-libraries/Mouse/pull/12)
> * [arduino-libraries/Mouse#13](https://github.com/arduino-libraries/Mouse/pull/13)
> * [arduino-libraries/Mouse#15](https://github.com/arduino-libraries/Mouse/pull/15)

Okay, got it. Thank you so much for your reply.
