### ISSUE TITLE
Introduction : MicroPython examples and tools for Portenta from Ayan Biswas

### ISSUE THREAD

**Issue by ayan-biswas0412** [arduino/summer-of-code#99]
**Who am I and my background of working ?**

I am Ayan Biswas , a undergrad at Jadavpur University , Kolkata ,India  majoring in Electronics and Telecommunication Engineering .
As per my course curricula I have done several arduino projects using **Arduino uno , Raspberry Pie, jetson Nano** ranging from **opencv based trafiic signal detection car** , basic line follower , bluetooth module based car and a **smart door lock system using NFC cards** etc. My comfortable programming languages are C/C++ , pyhton and also i posses knowledge of maintaining database (MySQL, POSTGREsql etc )and i also comfortable in web developing .

**What I can do in GSOC '20 for Arduino ?**

I can work in the areas of  **writing MicroPython examples and tools for Portenta** again as my major subject is fully related to this project so i want to do this as i think i am capable for this ,

Reply me if you are interested and i will upload my complete proposal for GSOC 2020 shortly.

Also see my profiles :
Website : https://ayan-portfolio.firebaseapp.com/
Linkedin : https://www.linkedin.com/in/ayanbiswas-juetceug/
Blog : https://ayanbiswas291395828.wordpress.com/
Medium : https://medium.com/@ayanbiswas184
**Also check my College Recommendation Letter** : [Click here](https://drive.google.com/file/d/1PhfqCEmsWaCojXG-VtHo-gsZln_1wDaY/view?usp=sharing)
Thanking you,
I will be highly obliged if you appoint me in for this project .

Regards from,

AYAN BISWAS,
UG Student at 
Department of Electronics and Telecommunication Engineering
Faculty of Engineering Technology
Jadavpur University

**Comment by ayan-biswas0412** [comment]
I have written this short code i don't know is this the right start for your project or not @alranel Please guide me about that what kind of work is really needed for Portenta and what type of project proposal do you expect from me  such that i can turn in a right direction for GSOC'20 .

**This program is about the Driver Code for Adafruit neo pixels (WS2812 chip)**
```
# driver for Adafruit neo pixels (WS2812 chip)
import pyb

class NeoPixel:
    def __init__(self, spi, n):
        spi.init(spi.MASTER, baudrate=2625000)
        spi.send(0)
        self.spi = spi
        self.buf = bytearray(9 * n + 1)
        self.clear()

    def __len__(self):
        return (len(self.buf) - 1) // 9

    def __setitem__(self, idx, val):
        idx *= 9
        self.fillword(idx, val[1]) # green
        self.fillword(idx + 3, val[0]) # red
        self.fillword(idx + 6, val[2]) # blue

    def clear(self):
        for i in range(len(self)):
            self[i] = (0, 0, 0)

    def send(self):
        self.spi.send(self.buf)

    def fillword(self, idx, val):
        expval = 0
        for i in range(8):
            expval <<= 3
            if val & 0x80:
                expval |= 0b110
            else:
                expval |= 0b100
            val <<= 1
        self.buf[idx] = expval >> 16
        self.buf[idx + 1] = expval >> 8
        self.buf[idx + 2] = expval

# creating the  driver on SPI(1) with 8 pixels

ws = NeoPixel(pyb.SPI(1), 8)

# scroll one to a  white pixel
for i in range(48):
    ws.clear()
    ws[i % len(ws)] = (64, 64, 64)
    ws.send()
    pyb.delay(50)

# turn all the  pixels off
ws.clear()
ws.send()
```

Also I am quite  new in this open source project environment and i have worked previously in Girsscript Summer of Code (GsSOC 2020) as my first open source project that was also an **Arduino UNO Based Water management System .**

Now i will be highly obliged if i can contribute for the new Portenta

**Comment by ayan-biswas0412** [comment]
@alranel Can you please guide that what things must be included in my final GSoC '20 project proposal , actually i want to know that what things you want from me for this particular idea mentioned #99 
Please guide me as early as possible .

**Comment by ayan-biswas0412** [comment]
I have shared my draft proposal through my Dashboard of GSoC'20 Please mention in the comment of the draft if anything modification is required @alranel

**Comment by alranel** [comment]
Hello @ayan-biswas0412, and welcome. Your proposal is a good start, so keep improving it in order to add more details about your project. Make sure you follow the application guide contained in this repository.

**Comment by ayan-biswas0412** [comment]
> Hello @ayan-biswas0412, and welcome. Your proposal is a good start, so keep improving it in order to add more details about your project. Make sure you follow the application guide contained in this repository.

Thank you, sir, for your compliment. I will do all minute editings in my proposal which are necessary for this project and it will be submitted by 31st of March before 23:00 IST and please comment on the sections in my proposal such that I can rectify to a great level.
**I have followed all the portions that are mentioned in the project proposal sample, and I will be highly obliged if you guide me in that portions if I have done something wrong in the project proposal that is not up to the mark.** 

Thank you again for your kind reply.

**Comment by ayan-biswas0412** [comment]
@alranel  I have updated my project timeframe in my Project Proposal in the  Schedule of Deliverables section for this project as per the new timeframe guidelines received from Google on Mar 24, 2020, 11:29 AM (IST)

**Comment by ayan-biswas0412** [comment]
My Contribution relevant to this project [Check #47](https://github.com/arduino-libraries/Servo/pull/47)
I have added a **Micropython example for Sweep of Servo** , Take it as my very initial contribution to the Portenta Project.

**Comment by ayan-biswas0412** [comment]
My Contribution relevant to this project [Check #53](https://github.com/arduino-libraries/Servo/pull/53)
I have added a Micropython example for controlling of Servo with a potentiometer , Take it as my second  contribution to the Portenta Project.

**Comment by ayan-biswas0412** [comment]
Hello, @alranel I have almost finalized my project proposal if anything clarification needed for my detailed project plan or anything related documentation clarification or in my milestones if you find anything wrong please comment on my proposal because only a few days are left and we the participants are at the eleventh hour.

**Also check my College Recommendation Letter** : [Click here](https://drive.google.com/file/d/1PhfqCEmsWaCojXG-VtHo-gsZln_1wDaY/view?usp=sharing)

**Comment by ayan-biswas0412** [comment]
@alranel please let me know if there is any codebase ready to take some initial action regarding GSoC like just understanding the codebase for the new portenta board

**Comment by ayan-biswas0412** [comment]
Hope you are Safe and Healthy in this pandemic situation and I have emailed you once but didn't get any reply.
Please let me know if there is any slack channel or any IRC for this project
